<?php
/** Opportunity Engine event invitations, artist responses, and owner overview. */
if (!defined('ABSPATH')) { exit; }
final class Elev8_OS_Opportunity_Module {
 const SLUG='elev8-opportunities';
 public static function init(): void { add_action('admin_menu',[__CLASS__,'menu'],34); add_action('admin_init',['Elev8_OS_Opportunity_Service','maybe_upgrade']); add_action('admin_init',['Elev8_OS_Opportunity_Participation_Service','maybe_upgrade']); add_action('admin_post_elev8_os_create_event_opportunity',[__CLASS__,'create']); add_action('admin_post_elev8_os_opportunity_response',[__CLASS__,'respond']); add_action('elev8_os_artist_dashboard_after_header',[__CLASS__,'artist_panel']); add_action('admin_enqueue_scripts',[__CLASS__,'admin_assets']); }
 public static function activate(): void { Elev8_OS_Opportunity_Service::activate(); Elev8_OS_Opportunity_Participation_Service::activate(); }
 public static function menu(): void { add_submenu_page('elev8-os',__('Opportunities','elev8-os'),__('Opportunities','elev8-os'),'manage_options',self::SLUG,[__CLASS__,'render']); }
 public static function admin_assets(string $hook): void { if($hook==='elev8-os_page_'.self::SLUG) wp_enqueue_style('elev8-os-opportunities',ELEV8_OS_URL.'assets/css/opportunities.css',[],ELEV8_OS_VERSION); }
 public static function create(): void { if(!current_user_can('manage_options'))wp_die(esc_html__('Permission denied.','elev8-os')); check_admin_referer('elev8_os_create_event_opportunity'); $p=wp_unslash($_POST); $id=Elev8_OS_Opportunity_Service::save_opportunity(['type'=>'event','title'=>$p['title']??'','category'=>$p['category']??'Event','description'=>$p['description']??'','status'=>'scheduled','preferred_day'=>$p['event_date']??'','preferred_time'=>$p['event_time']??'','internal_notes'=>$p['location']??'']); $invited=0; if($id>0){ foreach(Elev8_OS_Opportunity_Participation_Service::artist_users() as $a){$iid=Elev8_OS_Opportunity_Participation_Service::invite_user($id,(int)$a['ID'],(int)$a['artist_id']); if($iid){$invited++; if(!empty($p['send_email'])&&is_email($a['user_email'])) self::email_invite($a,$id,(string)($p['title']??''),(string)($p['event_date']??''));}} Elev8_OS_Opportunity_Activity_Service::record($id,'artists_invited',__('Artists invited','elev8-os'),sprintf(__('%d artists invited.','elev8-os'),$invited)); } wp_safe_redirect(add_query_arg(['page'=>self::SLUG,'created'=>$id>0?1:0,'invited'=>$invited],admin_url('admin.php'))); exit; }
 private static function email_invite(array $artist,int $id,string $title,string $date): void { $url=Elev8_OS_Portal_Page_Manager::get_url('dashboard'); $name=(string)($artist['display_name']??__('Artist','elev8-os')); $subject=sprintf(__('New Elev8 opportunity: %s','elev8-os'),$title); $message=sprintf("Hi %s,\n\nWe have a new opportunity coming up: %s%s.\n\nOpen your Elev8 OS dashboard to confirm whether you would like to attend:\n%s\n\nElev8 Arts",$name,$title,$date!==''?' on '.wp_date(get_option('date_format'),strtotime($date)):'',$url); Elev8_OS_Notification_Service::send_email((string)$artist['user_email'],$subject,$message); }
 public static function respond(): void { if(!is_user_logged_in())auth_redirect(); $id=absint($_POST['opportunity_id']??0); check_admin_referer('elev8_os_opportunity_response_'.$id); $status=sanitize_key((string)($_POST['response']??'')); $ok=Elev8_OS_Opportunity_Participation_Service::respond($id,get_current_user_id(),$status); if($ok) Elev8_OS_Opportunity_Activity_Service::record($id,'artist_response',__('Artist response received','elev8-os'),$status); wp_safe_redirect(add_query_arg('opportunity_response',$ok?'saved':'error',Elev8_OS_Portal_Page_Manager::get_url('dashboard'))); exit; }
 public static function artist_panel(): void { $items=Elev8_OS_Opportunity_Participation_Service::for_user(get_current_user_id()); if(!$items)return; $item=$items[0]; $status=(string)$item['status']; ?>
 <section class="elev8-opportunity-callout"><div><p class="elev8-eyebrow"><?php esc_html_e('Upcoming opportunity','elev8-os'); ?></p><h2><?php echo esc_html($item['title']); ?></h2><p><?php echo esc_html(trim(($item['event_date']??'').' '.($item['event_time']??''))); ?><?php if(!empty($item['internal_notes'])) echo ' · '.esc_html($item['internal_notes']); ?></p><?php if(!empty($item['description'])):?><p><?php echo esc_html($item['description']); ?></p><?php endif;?></div>
 <div class="elev8-opportunity-response"><span class="elev8-response-status"><?php echo esc_html(ucwords(str_replace('_',' ',$status))); ?></span><?php if(!in_array($status,['confirmed','declined'],true)): ?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="elev8_os_opportunity_response"><input type="hidden" name="opportunity_id" value="<?php echo (int)$item['opportunity_id']; ?>"><?php wp_nonce_field('elev8_os_opportunity_response_'.(int)$item['opportunity_id']); ?><button name="response" value="confirmed" class="button button-primary"><?php esc_html_e("I'll Be There",'elev8-os'); ?></button><button name="response" value="interested" class="button"><?php esc_html_e("I'm Interested",'elev8-os'); ?></button><button name="response" value="declined" class="button"><?php esc_html_e("Can't Attend",'elev8-os'); ?></button><button name="response" value="remind_later" class="button-link"><?php esc_html_e('Remind Me Later','elev8-os'); ?></button></form><?php endif;?></div></section><?php }
 public static function render(): void { if(!current_user_can('manage_options'))wp_die(esc_html__('Permission denied.','elev8-os')); $all=Elev8_OS_Opportunity_Service::all(); ?>
 <div class="wrap elev8-opportunities"><h1><?php esc_html_e('Opportunity Engine','elev8-os'); ?></h1><p><?php esc_html_e('Create an event once, invite every connected artist, and track responses without chasing people by text.','elev8-os'); ?></p><?php if(isset($_GET['created'])):?><div class="notice notice-success"><p><?php echo esc_html(sprintf(__('Opportunity created and %d artists invited.','elev8-os'),absint($_GET['invited']??0))); ?></p></div><?php endif;?>
 <div class="elev8-op-grid"><section class="elev8-op-panel"><h2><?php esc_html_e('Create Event Opportunity','elev8-os'); ?></h2><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="elev8_os_create_event_opportunity"><?php wp_nonce_field('elev8_os_create_event_opportunity'); ?><p><label><?php esc_html_e('Event name','elev8-os'); ?><input required class="widefat" name="title"></label></p><p><label><?php esc_html_e('Opportunity type','elev8-os'); ?><select class="widefat" name="category"><option>Art Walk</option><option>Private Party</option><option>Dispensary Event</option><option>Gallery Event</option><option>Vendor Event</option><option>Corporate Event</option><option>Community Event</option></select></label></p><div class="elev8-op-two"><p><label><?php esc_html_e('Date','elev8-os'); ?><input required type="date" class="widefat" name="event_date"></label></p><p><label><?php esc_html_e('Time','elev8-os'); ?><input type="text" class="widefat" name="event_time" placeholder="11:00 AM – 4:00 PM"></label></p></div><p><label><?php esc_html_e('Location','elev8-os'); ?><input class="widefat" name="location"></label></p><p><label><?php esc_html_e('Message to artists','elev8-os'); ?><textarea class="widefat" rows="4" name="description"></textarea></label></p><p><label><input type="checkbox" name="send_email" value="1" checked> <?php esc_html_e('Email every connected artist now','elev8-os'); ?></label></p><p><button class="button button-primary button-hero"><?php esc_html_e('Create and Invite Artists','elev8-os'); ?></button></p></form></section>
 <section class="elev8-op-panel"><h2><?php esc_html_e('Event Opportunities','elev8-os'); ?></h2><?php $found=false; foreach($all as $o){if(($o['type']??'')!=='event')continue;$found=true;$c=Elev8_OS_Opportunity_Participation_Service::counts((int)$o['id']);?><article class="elev8-op-row"><div><strong><?php echo esc_html($o['title']); ?></strong><p><?php echo esc_html(($o['category']??'Event').' · '.($o['preferred_day']??'')); ?></p></div><div class="elev8-op-counts"><span><?php echo (int)$c['confirmed']; ?> <?php esc_html_e('confirmed','elev8-os'); ?></span><span><?php echo (int)$c['interested']; ?> <?php esc_html_e('interested','elev8-os'); ?></span><span><?php echo (int)$c['pending']; ?> <?php esc_html_e('pending','elev8-os'); ?></span></div></article><?php } if(!$found):?><p><?php esc_html_e('No event opportunities yet. Create the first one here.','elev8-os'); ?></p><?php endif;?></section></div></div><?php }
}
