<?php
if (!defined('ABSPATH')) { exit; }
final class Elev8_OS_Gallery_Operations_Module {
    public static function init(): void {
        add_action('admin_menu',[__CLASS__,'menu'],20); add_action('admin_enqueue_scripts',[__CLASS__,'assets']);
        add_action('admin_post_elev8_os_save_gallery_zone',[__CLASS__,'save_zone']); add_action('admin_post_elev8_os_create_portal_rack',[__CLASS__,'create_rack']); add_action('admin_post_elev8_os_place_asset',[__CLASS__,'place']); add_action('admin_post_elev8_os_remove_asset_display',[__CLASS__,'remove']);
        add_shortcode('elev8_artist_gallery_status',[__CLASS__,'artist_status']);
    }
    public static function menu(): void { add_submenu_page('elev8-os','Gallery Operations','Gallery Operations','manage_options','elev8-gallery-operations',[__CLASS__,'render']); }
    public static function assets(string $hook): void { if($hook!=='elev8-os_page_elev8-gallery-operations') return; wp_enqueue_style('elev8-gallery-operations',ELEV8_OS_URL.'assets/css/gallery-operations.css',[],ELEV8_OS_VERSION); }
    public static function render(): void {
        if(!current_user_can('manage_options')) wp_die('Not allowed.'); $artist_filter=absint($_GET['artist_filter']??0); $d=Elev8_OS_Gallery_Operations_Service::dashboard($artist_filter); $zones=$d['zones']; $notice=sanitize_text_field((string)($_GET['gallery_notice']??'')); ?>
        <div class="wrap elev8-gallery-ops"><header class="elev8-go-header"><div><p class="eyebrow">ELEV8 OS 9.0.1</p><h1>Gallery Operations</h1><p>Know where every piece is, what needs attention, and how the gallery is performing.</p></div><span class="mode-pill">Gallery Mode</span></header>
        <?php if($notice):?><div class="notice notice-success is-dismissible"><p><?php echo esc_html($notice);?></p></div><?php endif;?>
        <form method="get" class="go-artist-filter"><input type="hidden" name="page" value="elev8-gallery-operations"><label for="artist_filter"><strong>Filter artwork by artist</strong></label><select id="artist_filter" name="artist_filter" onchange="this.form.submit()"><option value="0">All artists</option><?php foreach($d['artists'] as $artist):?><option value="<?php echo absint($artist['ID']);?>" <?php selected($artist_filter,absint($artist['ID']));?>><?php echo esc_html($artist['display_name'].' — '.$artist['user_email']);?></option><?php endforeach;?></select><?php if($artist_filter):?><a class="button" href="<?php echo esc_url(admin_url('admin.php?page=elev8-gallery-operations'));?>">Clear filter</a><?php endif;?></form>
        <section class="go-kpis"><?php foreach([['Available',$d['summary']['available']??0],['Reserved',$d['summary']['reserved']??0],['On display',count($d['placed'])],['Available value','$'.number_format_i18n((float)($d['summary']['available_value']??0),2)],['Needs placement',count($d['unplaced'])]] as $k):?><article><strong><?php echo esc_html((string)$k[1]);?></strong><span><?php echo esc_html($k[0]);?></span></article><?php endforeach;?></section>
        <section class="go-grid"><article class="go-card go-wide"><div class="go-card-head"><div><h2>Gallery floor</h2><p>Current display zones and capacity.</p></div></div><div class="zone-grid"><?php foreach($zones as $z):?><div class="zone <?php echo $z['zone_type']==='artist_portal_rack'?'portal-zone':'';?>"><div><strong><?php echo esc_html($z['name']);?></strong><small><?php echo esc_html(self::zone_type_label($z));?><?php if(!empty($z['assigned_artist_user_id'])) echo ' · '.esc_html(get_the_author_meta('display_name',absint($z['assigned_artist_user_id'])));?></small></div><b><?php echo absint($z['piece_count']);?><?php echo absint($z['capacity'])?' / '.absint($z['capacity']):'';?></b><span><?php echo esc_html(ucfirst((string)($z['board_status']??'available')));?> · <?php echo esc_html('$'.number_format_i18n((float)$z['display_value'],2));?> displayed</span></div><?php endforeach;?></div></article>
        <article class="go-card"><h2>Add display zone</h2><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>" class="stack"><?php wp_nonce_field('elev8_save_gallery_zone');?><input type="hidden" name="action" value="elev8_os_save_gallery_zone"><label>Name<input required name="name" placeholder="North Wall"></label><label>Type<select name="zone_type"><option value="wall">Wall</option><option value="window">Window</option><option value="case">Case</option><option value="display">Display</option><option value="room">Room</option><option value="storage">Storage</option><option value="artist_portal_rack">Artist Portal Rack position</option></select></label><label>Capacity<input type="number" min="0" name="capacity"></label><input type="hidden" name="active" value="1"><button class="button button-primary">Add zone</button></form></article></section>
        <section class="go-card portal-rack-setup"><div class="go-card-head"><div><h2>Artist Portal racks</h2><p>Create every numbered board and both book-style sides for each physical rack. You can create Rack 1 and Rack 2 separately using the actual number of boards on each rack.</p></div></div><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>" class="rack-form"><?php wp_nonce_field('elev8_create_portal_rack');?><input type="hidden" name="action" value="elev8_os_create_portal_rack"><label>Rack number<input required type="number" min="1" max="99" name="rack_number" value="1"></label><label>Number of art boards<input required type="number" min="1" max="100" name="board_count" placeholder="Example: 12"></label><label>Artwork capacity per side<input required type="number" min="1" max="20" name="capacity_per_side" value="1"></label><button class="button button-primary">Create rack positions</button></form><p class="description">Each board creates Side A and Side B. Example: Artist Portal Rack 2 → Art Board 4 → Side B.</p></section>
        <section class="go-grid"><article class="go-card"><h2>Needs placement</h2><p><?php echo $artist_filter?'Unplaced artwork for the selected artist.':'Artwork currently at Elev8 without an active display zone.';?></p><?php if(!$d['unplaced']):?><div class="empty">No matching artwork needs placement.</div><?php else:?><div class="asset-list"><?php foreach($d['unplaced'] as $a): self::asset_form($a,$zones); endforeach;?></div><?php endif;?></article>
        <article class="go-card"><h2>On display</h2><p><?php echo $artist_filter?'Displayed artwork for the selected artist.':'Move a piece or remove it from the floor.';?></p><?php if(!$d['placed']):?><div class="empty">No matching artwork is currently displayed.</div><?php else:?><div class="asset-list"><?php foreach($d['placed'] as $a): self::asset_form($a,$zones,true); endforeach;?></div><?php endif;?></article></section>
        <section class="go-card"><h2>Morning gallery brief</h2><div class="brief"><p><strong><?php echo count($d['unplaced']);?></strong> pieces need placement.</p><p><strong><?php echo absint($d['summary']['reserved']??0);?></strong> pieces are reserved.</p><p><strong><?php echo count(array_filter($zones,fn($z)=>absint($z['capacity'])>0 && absint($z['piece_count'])<absint($z['capacity'])));?></strong> zones have open capacity.</p></div></section></div><?php
    }
    private static function zone_type_label(array $z): string { if(($z['zone_type']??'')==='artist_portal_rack') return sprintf('Artist Portal Rack %d · Board %d · Side %s',absint($z['rack_number']),absint($z['board_number']),esc_html((string)$z['side_label'])); return ucfirst(str_replace('_',' ',(string)($z['zone_type']??'display'))); }
    private static function asset_form(array $a,array $zones,bool $placed=false): void { ?>
        <div class="asset-row"><div><strong><?php echo esc_html($a['title']);?></strong><small><?php echo esc_html((string)($a['artist_name']??get_the_author_meta('display_name',absint($a['owner_user_id']))));?> · <?php echo esc_html(ucfirst($a['status']));?><?php if(!empty($a['zone_name'])) echo ' · '.esc_html($a['zone_name']);?></small></div><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><?php wp_nonce_field('elev8_place_asset_'.$a['id']);?><input type="hidden" name="action" value="elev8_os_place_asset"><input type="hidden" name="asset_id" value="<?php echo absint($a['id']);?>"><select name="zone_id" required><option value="">Choose zone</option><?php foreach($zones as $z): $assigned=absint($z['assigned_artist_user_id']??0); $wrong=$assigned && $assigned!==absint($a['owner_user_id']);?><option value="<?php echo absint($z['id']);?>" <?php selected(absint($a['zone_id']??0),absint($z['id']));?> <?php disabled($wrong || ($z['board_status']??'')==='maintenance');?>><?php echo esc_html($z['name'].($wrong?' — reserved for another artist':''));?></option><?php endforeach;?></select><input name="position_label" value="<?php echo esc_attr((string)($a['position_label']??''));?>" placeholder="Position / shelf"><button class="button button-primary"><?php echo $placed?'Move':'Place';?></button></form><?php if($placed):?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><?php wp_nonce_field('elev8_remove_asset_'.$a['id']);?><input type="hidden" name="action" value="elev8_os_remove_asset_display"><input type="hidden" name="asset_id" value="<?php echo absint($a['id']);?>"><select name="placement_status"><option value="removed">Remove</option><option value="storage">Move to storage</option><option value="pickup">Needs pickup</option></select><button class="button">Update</button></form><?php endif;?></div><?php }
    public static function save_zone(): void { self::guard(); check_admin_referer('elev8_save_gallery_zone'); $r=Elev8_OS_Gallery_Operations_Service::save_zone($_POST); self::redirect(is_wp_error($r)?$r->get_error_message():'Display zone added.'); }
    public static function create_rack(): void { self::guard(); check_admin_referer('elev8_create_portal_rack'); $r=Elev8_OS_Gallery_Operations_Service::create_artist_portal_rack(absint($_POST['rack_number']??0),absint($_POST['board_count']??0),absint($_POST['capacity_per_side']??1)); self::redirect(is_wp_error($r)?$r->get_error_message():sprintf('%d Artist Portal board sides are ready.',absint($r))); }
    public static function place(): void { self::guard(); $id=absint($_POST['asset_id']??0); check_admin_referer('elev8_place_asset_'.$id); $r=Elev8_OS_Gallery_Operations_Service::place_asset($id,absint($_POST['zone_id']??0),wp_unslash($_POST['position_label']??'')); self::redirect(is_wp_error($r)?$r->get_error_message():'Artwork placement updated.'); }
    public static function remove(): void { self::guard(); $id=absint($_POST['asset_id']??0); check_admin_referer('elev8_remove_asset_'.$id); Elev8_OS_Gallery_Operations_Service::remove_from_display($id,sanitize_key($_POST['placement_status']??'removed')); self::redirect('Artwork display status updated.'); }
    private static function guard(): void { if(!current_user_can('manage_options')) wp_die('Not allowed.'); }
    private static function redirect(string $m): void { $url=add_query_arg('gallery_notice',$m,admin_url('admin.php?page=elev8-gallery-operations')); if(!empty($_POST['artist_filter'])) $url=add_query_arg('artist_filter',absint($_POST['artist_filter']),$url); wp_safe_redirect($url); exit; }
    public static function artist_status(): string { if(!is_user_logged_in()) return ''; $s=Elev8_OS_Gallery_Operations_Service::owner_snapshot(get_current_user_id()); ob_start();?><section class="elev8-artist-gallery-status"><h2>Where is my artwork?</h2><?php if(!$s['rows']):?><p>No artwork records yet.</p><?php else:?><div class="elev8-table-wrap"><table><thead><tr><th>Artwork</th><th>Status</th><th>Location</th><th>Days displayed</th></tr></thead><tbody><?php foreach($s['rows'] as $r):?><tr><td><?php echo esc_html($r['title']);?></td><td><?php echo esc_html(ucfirst($r['status']));?></td><td><?php echo esc_html($r['zone_name']?:'Not currently displayed');?></td><td><?php echo $r['days_displayed']!==null?absint($r['days_displayed']):'—';?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section><?php return (string)ob_get_clean(); }
}
