<?php
/** CEO-facing read-only integration diagnostics. */
if (!defined('ABSPATH')) { exit; }
final class Elev8_OS_Integration_Engine_Module {
    private const OPTION_PAGE_ID='elev8_os_integration_engine_page_id'; private const SLUG='integration-engine'; private const SHORTCODE='elev8_integration_engine';
    public static function init(): void { add_action('admin_menu',[__CLASS__,'admin_menu'],31); add_action('init',[__CLASS__,'ensure_page'],38); add_shortcode(self::SHORTCODE,[__CLASS__,'shortcode']); add_action('wp_enqueue_scripts',[__CLASS__,'assets']); add_action('admin_enqueue_scripts',[__CLASS__,'admin_assets']); add_filter('elev8_os_application_shell_frontend',[__CLASS__,'shell']); add_filter('elev8_os_command_palette_commands',[__CLASS__,'command'],28,2); }
    public static function activate(): void { self::ensure_page(true); }
    public static function admin_menu(): void { add_submenu_page('elev8-os',__('Integration Engine','elev8-os'),__('Integration Engine','elev8-os'),'manage_options','elev8-integration-engine',[__CLASS__,'render_admin']); }
    public static function ensure_page(bool $force=false): void { $id=absint(get_option(self::OPTION_PAGE_ID)); if($id&&get_post($id)instanceof WP_Post)return; $page=get_page_by_path(self::SLUG,OBJECT,'page'); if($page instanceof WP_Post&&$page->post_status!=='trash'){update_option(self::OPTION_PAGE_ID,(int)$page->ID,false);return;} if(!$force&&!current_user_can('manage_options'))return; $id=wp_insert_post(['post_title'=>__('Integration Engine','elev8-os'),'post_name'=>self::SLUG,'post_content'=>'['.self::SHORTCODE.']','post_status'=>'publish','post_type'=>'page','post_author'=>get_current_user_id(),'comment_status'=>'closed'],true); if(!is_wp_error($id)&&$id>0)update_option(self::OPTION_PAGE_ID,(int)$id,false); }
    public static function url(): string { $id=absint(get_option(self::OPTION_PAGE_ID)); return $id?(string)get_permalink($id):home_url('/'.self::SLUG.'/'); }
    public static function shell(bool $show): bool { return $show||is_page(absint(get_option(self::OPTION_PAGE_ID)))||is_page(self::SLUG); }
    public static function assets(): void { if(self::shell(false))wp_enqueue_style('elev8-integration-engine',ELEV8_OS_URL.'assets/css/integration-engine.css',[],ELEV8_OS_VERSION); }
    public static function admin_assets(string $hook): void { if($hook==='elev8-os_page_elev8-integration-engine')wp_enqueue_style('elev8-integration-engine',ELEV8_OS_URL.'assets/css/integration-engine.css',[],ELEV8_OS_VERSION); }
    public static function shortcode(): string { if(!is_user_logged_in())return '<p>'.esc_html__('Please sign in.','elev8-os').'</p>'; if(!current_user_can('manage_options'))return '<p>'.esc_html__('Integration diagnostics are currently available to the CEO and administrators.','elev8-os').'</p>'; return self::content(); }
    public static function render_admin(): void { if(!current_user_can('manage_options'))wp_die(esc_html__('Permission denied.','elev8-os')); echo '<div class="wrap">'.self::content().'</div>'; }
    private static function content(): string { $d=Elev8_OS_Integration_Adapter_Service::diagnostics(); ob_start(); ?><main class="elev8-integration"><header><p><?php esc_html_e('Integration Engine','elev8-os'); ?></p><h1><?php esc_html_e('Authoritative systems, connected safely','elev8-os'); ?></h1><span><?php esc_html_e('Elev8 OS references WooCommerce and Amelia records without copying their source data.','elev8-os'); ?></span></header><section class="elev8-integration__grid"><article><h2>WooCommerce</h2><strong><?php echo !empty($d['woocommerce']['available'])?esc_html__('Connected','elev8-os'):esc_html__('Unavailable','elev8-os'); ?></strong><dl><div><dt><?php esc_html_e('Products','elev8-os'); ?></dt><dd><?php echo esc_html((string)$d['woocommerce']['products']); ?></dd></div><div><dt><?php esc_html_e('Orders','elev8-os'); ?></dt><dd><?php echo esc_html((string)$d['woocommerce']['orders']); ?></dd></div></dl><p><?php esc_html_e('Commerce records remain owned by WooCommerce.','elev8-os'); ?></p></article><article><h2>Amelia</h2><strong><?php echo !empty($d['amelia']['appointments']['available'])?esc_html__('Connected','elev8-os'):esc_html__('Unavailable','elev8-os'); ?></strong><dl><div><dt><?php esc_html_e('Appointments','elev8-os'); ?></dt><dd><?php echo esc_html((string)$d['amelia']['appointments']['count']); ?></dd></div><div><dt><?php esc_html_e('Bookings','elev8-os'); ?></dt><dd><?php echo esc_html((string)$d['amelia']['bookings']['count']); ?></dd></div><div><dt><?php esc_html_e('Services','elev8-os'); ?></dt><dd><?php echo esc_html((string)$d['amelia']['services']['count']); ?></dd></div></dl><p><?php esc_html_e('Scheduling and booking records remain owned by Amelia.','elev8-os'); ?></p></article></section><section class="elev8-integration__panel"><h2><?php esc_html_e('Business Graph adapters','elev8-os'); ?></h2><p><?php esc_html_e('Products, orders, bookings, and classes can now open as read-only Universal Workspaces with stable source references. Elev8 OS may attach work, conversations, relationships, and intelligence without cloning the source record.','elev8-os'); ?></p></section></main><?php return (string)ob_get_clean(); }
    public static function command(array $commands,WP_User $user): array { if(user_can($user,'manage_options'))$commands[]=['id'=>'integration_engine','label'=>__('Integration Engine','elev8-os'),'description'=>__('Review WooCommerce and Amelia Business Graph adapters.','elev8-os'),'url'=>self::url(),'group'=>'architecture','icon'=>'🔌','type'=>'command']; return $commands; }
}
