<?php
if (!defined('ABSPATH')) { exit; }
final class Elev8_OS_Marketing_Module {
    public static function init(): void {
        add_shortcode('elev8_artist_marketing',[__CLASS__,'shortcode']);
        add_action('admin_post_elev8_os_marketing_save_draft',[__CLASS__,'save_draft']);
        add_action('admin_post_elev8_os_marketing_send_test',[__CLASS__,'send_test']);
        add_action('admin_post_elev8_os_marketing_send',[__CLASS__,'send']);
        add_action('wp_enqueue_scripts',[__CLASS__,'assets']);
        add_action('admin_menu',[__CLASS__,'admin_menu'],40);
        add_action('admin_post_elev8_os_save_art_walk_settings',[__CLASS__,'save_art_walk_settings']);
        add_action('admin_post_elev8_os_mark_art_walk_registered',[__CLASS__,'mark_art_walk_registered']);
    }
    public static function assets(): void { if(Elev8_OS_Portal_Page_Manager::is_current_page('marketing')){wp_enqueue_style('dashicons');wp_enqueue_style('elev8-os-marketing',ELEV8_OS_URL.'assets/css/artist-marketing.css',[],ELEV8_OS_VERSION);wp_enqueue_style('elev8-os-growth-tools',ELEV8_OS_URL.'assets/css/artist-growth-tools.css',[],ELEV8_OS_VERSION);} }
    public static function admin_menu(): void {
        add_submenu_page('elev8-os',__('Artist Growth Settings','elev8-os'),__('Growth Settings','elev8-os'),'manage_options','elev8-growth-settings',[__CLASS__,'render_settings']);
    }
    public static function render_settings(): void {
        if(!current_user_can('manage_options')){wp_die(esc_html__('You do not have permission.','elev8-os'));}
        $settings=self::art_walk_settings(); ?>
        <div class="wrap"><h1><?php esc_html_e('Artist Growth Settings','elev8-os'); ?></h1><h2><?php esc_html_e('Art Walk Assistant','elev8-os'); ?></h2>
        <p><?php esc_html_e('These owner-controlled details power the artist dashboard tickler and Art Walk email template.','elev8-os'); ?></p>
        <?php if(isset($_GET['saved'])):?><div class="notice notice-success"><p><?php esc_html_e('Growth settings saved.','elev8-os'); ?></p></div><?php endif;?>
        <form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="elev8_os_save_art_walk_settings"><?php wp_nonce_field('elev8_os_save_art_walk_settings'); ?>
        <table class="form-table"><tr><th><?php esc_html_e('Enable Art Walk Assistant','elev8-os'); ?></th><td><label><input type="checkbox" name="active" value="1" <?php checked(!empty($settings['active'])); ?>> <?php esc_html_e('Show artists the monthly registration tickler','elev8-os'); ?></label></td></tr>
        <tr><th><?php esc_html_e('Next event date','elev8-os'); ?></th><td><input type="date" name="event_date" value="<?php echo esc_attr($settings['event_date']); ?>"></td></tr>
        <tr><th><?php esc_html_e('Registration opens','elev8-os'); ?></th><td><input type="date" name="open_date" value="<?php echo esc_attr($settings['open_date']); ?>"></td></tr>
        <tr><th><?php esc_html_e('Registration deadline','elev8-os'); ?></th><td><input type="date" name="deadline" value="<?php echo esc_attr($settings['deadline']); ?>"></td></tr>
        <tr><th><?php esc_html_e('Registration URL','elev8-os'); ?></th><td><input class="regular-text" type="url" name="registration_url" value="<?php echo esc_attr($settings['registration_url']); ?>"></td></tr>
        <tr><th><?php esc_html_e('Expected visitors','elev8-os'); ?></th><td><input class="regular-text" type="text" name="expected_visitors" value="<?php echo esc_attr($settings['expected_visitors']); ?>" placeholder="350–500"></td></tr></table><?php submit_button(__('Save Growth Settings','elev8-os')); ?></form></div><?php
    }
    public static function save_art_walk_settings(): void {
        if(!current_user_can('manage_options')){wp_die(esc_html__('You do not have permission.','elev8-os'));}check_admin_referer('elev8_os_save_art_walk_settings');
        update_option('elev8_os_art_walk_settings',['active'=>!empty($_POST['active']),'event_date'=>sanitize_text_field(wp_unslash($_POST['event_date']??'')),'open_date'=>sanitize_text_field(wp_unslash($_POST['open_date']??'')),'deadline'=>sanitize_text_field(wp_unslash($_POST['deadline']??'')),'registration_url'=>esc_url_raw(wp_unslash($_POST['registration_url']??'')),'expected_visitors'=>sanitize_text_field(wp_unslash($_POST['expected_visitors']??''))],false);
        wp_safe_redirect(add_query_arg(['page'=>'elev8-growth-settings','saved'=>'1'],admin_url('admin.php')));exit;
    }
    /** @return array<string,mixed> */
    public static function art_walk_settings(): array { return wp_parse_args((array)get_option('elev8_os_art_walk_settings',[]),['active'=>false,'event_date'=>'','open_date'=>'','deadline'=>'','registration_url'=>'','expected_visitors'=>'']); }
    public static function should_show_art_walk_tickler(WP_User $user): bool {
        $s=self::art_walk_settings();if(empty($s['active'])||empty($s['registration_url'])){return false;}
        $event_month=!empty($s['event_date'])?substr((string)$s['event_date'],0,7):wp_date('Y-m');
        if((string)get_user_meta($user->ID,'elev8_os_art_walk_registered_'.$event_month,true)==='1'){return false;}
        $today=(int)wp_date('j');$weekday=(int)wp_date('N');
        $third_monday_day=15 + ((1-(int)wp_date('N',strtotime(wp_date('Y-m-15')))+7)%7);
        return $today >= $third_monday_day || (!empty($s['deadline']) && strtotime((string)$s['deadline']) >= current_time('timestamp'));
    }
    public static function render_art_walk_tickler(WP_User $user): void {
        if(!self::should_show_art_walk_tickler($user)){return;}$s=self::art_walk_settings();$event=!empty($s['event_date'])?wp_date(get_option('date_format'),strtotime((string)$s['event_date'])):__('Upcoming','elev8-os'); ?>
        <section class="elev8-dashboard-panel elev8-art-walk-tickler"><div class="elev8-panel-heading"><div><p class="elev8-eyebrow"><?php esc_html_e('Community Opportunity','elev8-os'); ?></p><h2><?php esc_html_e('Art Walk is coming up','elev8-os'); ?></h2><p class="elev8-panel-intro"><?php echo esc_html(sprintf(__('Next event: %s. Reserve your space and prepare the work you want visitors to discover.','elev8-os'),$event)); ?></p></div></div>
        <div class="elev8-art-walk-actions"><a class="button button-primary" href="<?php echo esc_url($s['registration_url']); ?>" target="_blank" rel="noopener noreferrer"><?php esc_html_e('Register for Art Walk','elev8-os'); ?></a><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="elev8_os_mark_art_walk_registered"><?php wp_nonce_field('elev8_os_mark_art_walk_registered'); ?><button class="button" type="submit"><?php esc_html_e('I Registered','elev8-os'); ?></button></form><?php if(!empty($s['expected_visitors'])):?><span><?php echo esc_html(sprintf(__('Expected visitors: %s','elev8-os'),$s['expected_visitors'])); ?></span><?php endif;?></div></section><?php
    }
    public static function mark_art_walk_registered(): void { if(!is_user_logged_in()){wp_die(esc_html__('Please log in.','elev8-os'));}check_admin_referer('elev8_os_mark_art_walk_registered');$s=self::art_walk_settings();$month=!empty($s['event_date'])?substr((string)$s['event_date'],0,7):wp_date('Y-m');update_user_meta(get_current_user_id(),'elev8_os_art_walk_registered_'.$month,'1');wp_safe_redirect(Elev8_OS_Portal_Page_Manager::get_url('dashboard'));exit; }
    public static function shortcode(): string {
        if(!is_user_logged_in()){return '<p>'.esc_html__('Please log in to use the Marketing Center.','elev8-os').'</p>';}
        $artist=wp_get_current_user();$templates=Elev8_OS_Marketing_Service::templates();$selected=sanitize_key($_GET['template']??'new_class');if(!isset($templates[$selected])){$selected='new_class';}$template=$templates[$selected];
        $audience=sanitize_key($_GET['audience']??'all');$audience_value=sanitize_text_field(wp_unslash($_GET['audience_value']??''));$preview=Elev8_OS_Marketing_Service::audience($artist,$audience,$audience_value);$tags=Elev8_OS_Marketing_Service::unique_tags($artist);$campaigns=Elev8_OS_Marketing_Service::campaigns((int)$artist->ID);
        $subject=sanitize_text_field(wp_unslash($_GET['subject']??$template['subject']));$message=sanitize_textarea_field(wp_unslash($_GET['message']??$template['message']));$promoted=esc_url_raw(wp_unslash($_GET['promoted_url']??''));$ref=Elev8_OS_Marketing_Service::referral_url((int)$artist->ID,$promoted);
        ob_start();?><div class="elev8-marketing-center"><?php Elev8_OS_Artist_Portal_Module::render_navigation('growth_studio'); ?>
        <header class="elev8-marketing-hero"><div><p class="elev8-eyebrow"><?php esc_html_e('Artist Growth Center','elev8-os'); ?></p><h1><?php esc_html_e('Marketing Center','elev8-os'); ?></h1><p><?php esc_html_e('Reconnect with verified students and help fill the next great Elev8 experience.','elev8-os'); ?></p></div><span><?php echo esc_html(sprintf(__('%d verified recipients','elev8-os'),(int)($preview['count']??0))); ?></span></header>
        <?php if(class_exists('Elev8_OS_Artist_Print_Center_Module')){echo Elev8_OS_Artist_Print_Center_Module::render_growth_entry('marketing');} ?>
        <?php if(isset($_GET['elev8_message'])):?><div class="elev8-marketing-notice"><?php echo esc_html(sanitize_text_field(wp_unslash($_GET['elev8_message']))); ?></div><?php endif; ?>
        <div class="elev8-marketing-grid"><main class="elev8-marketing-compose"><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>">
        <?php wp_nonce_field('elev8_os_marketing_action'); ?><input type="hidden" name="campaign_type" value="<?php echo esc_attr($selected); ?>">
        <section class="elev8-marketing-card"><h2><?php esc_html_e('1. Choose a template','elev8-os'); ?></h2><div class="elev8-template-grid"><?php foreach($templates as $key=>$t):?><a class="<?php echo $key===$selected?'is-active':''; ?>" href="<?php echo esc_url(add_query_arg('template',$key,Elev8_OS_Portal_Page_Manager::get_url('marketing'))); ?>"><strong><?php echo esc_html($t['label']); ?></strong></a><?php endforeach;?></div></section>
        <section class="elev8-marketing-card"><h2><?php esc_html_e('2. Choose your audience','elev8-os'); ?></h2><label><?php esc_html_e('Student segment','elev8-os'); ?><select name="audience_type" id="elev8-audience"><option value="all" <?php selected($audience,'all'); ?>><?php esc_html_e('All Students','elev8-os'); ?></option><option value="repeat" <?php selected($audience,'repeat'); ?>><?php esc_html_e('Repeat Students','elev8-os'); ?></option><option value="new" <?php selected($audience,'new'); ?>><?php esc_html_e('New Students — 30 days','elev8-os'); ?></option><option value="upcoming" <?php selected($audience,'upcoming'); ?>><?php esc_html_e('Upcoming Students','elev8-os'); ?></option><option value="inactive" <?php selected($audience,'inactive'); ?>><?php esc_html_e('Need Follow-up — 90+ days','elev8-os'); ?></option><option value="tag" <?php selected($audience,'tag'); ?>><?php esc_html_e('Students with Tag','elev8-os'); ?></option></select></label><label><?php esc_html_e('Tag, when using a tag audience','elev8-os'); ?><select name="audience_value"><option value=""><?php esc_html_e('Choose a tag','elev8-os'); ?></option><?php foreach($tags as $tag):?><option <?php selected($audience_value,$tag); ?>><?php echo esc_html($tag); ?></option><?php endforeach;?></select></label><p class="elev8-recipient-count"><?php echo esc_html(sprintf(__('%d unique verified email addresses will be considered.','elev8-os'),(int)($preview['count']??0))); ?></p></section>
        <section class="elev8-marketing-card"><h2><?php esc_html_e('3. Write the email','elev8-os'); ?></h2><label><?php esc_html_e('Subject','elev8-os'); ?><input type="text" name="subject" value="<?php echo esc_attr($subject); ?>" maxlength="255" required></label><label><?php esc_html_e('Message','elev8-os'); ?><textarea name="message" rows="12" required><?php echo esc_textarea($message); ?></textarea></label><p class="description"><?php esc_html_e('Available merge fields: {{first_name}}, {{artist_name}}, {{artist_profile}}, {{promotion_link}}','elev8-os'); ?></p></section>
        <section class="elev8-marketing-card"><h2><?php esc_html_e('4. Add a promotion or referral link','elev8-os'); ?></h2><label><?php esc_html_e('Class, artwork, artist, or event URL','elev8-os'); ?><input type="url" name="promoted_url" value="<?php echo esc_attr($promoted); ?>" placeholder="https://"></label><p><?php esc_html_e('Elev8 OS automatically adds your artist referral identity to this link. Detailed booking attribution arrives in 9.1.2.','elev8-os'); ?></p><?php if($ref!==''):?><code><?php echo esc_html($ref); ?></code><?php endif;?></section>
        <div class="elev8-marketing-actions"><button class="button" name="action" value="elev8_os_marketing_save_draft"><?php esc_html_e('Save Draft','elev8-os'); ?></button><button class="button" name="action" value="elev8_os_marketing_send_test"><?php esc_html_e('Send Test to Me','elev8-os'); ?></button><button class="button button-primary" name="action" value="elev8_os_marketing_send" onclick="return confirm('<?php echo esc_js(__('Send this email to the selected verified students?','elev8-os')); ?>')"><?php esc_html_e('Send Campaign','elev8-os'); ?></button></div></form></main>
        <aside class="elev8-marketing-history"><section class="elev8-marketing-card"><h2><?php esc_html_e('Campaign History','elev8-os'); ?></h2><?php if(!$campaigns):?><p><?php esc_html_e('No campaigns yet. Your drafts and sent emails will appear here.','elev8-os'); ?></p><?php else:foreach($campaigns as $c):?><article><strong><?php echo esc_html((string)$c['subject']); ?></strong><span><?php echo esc_html(ucwords(str_replace('_',' ',(string)$c['status']))); ?></span><small><?php echo esc_html(sprintf(__('Sent %1$d · Failed %2$d · Skipped %3$d','elev8-os'),(int)$c['sent_count'],(int)$c['failed_count'],(int)$c['skipped_count'])); ?></small><time><?php echo esc_html(wp_date(get_option('date_format'),strtotime((string)$c['created_at']))); ?></time></article><?php endforeach;endif;?></section><section class="elev8-marketing-card elev8-email-safety"><h2><?php esc_html_e('Safe Sending','elev8-os'); ?></h2><ul><li><?php esc_html_e('Uses your site’s configured WordPress/SMTP mail provider.','elev8-os'); ?></li><li><?php esc_html_e('Removes duplicate email addresses.','elev8-os'); ?></li><li><?php esc_html_e('Honors artist-specific unsubscribe requests.','elev8-os'); ?></li><li><?php esc_html_e('Maximum 250 recipients per campaign.','elev8-os'); ?></li></ul></section></aside></div></div><?php return (string)ob_get_clean();
    }
    public static function save_draft(): void { self::authorize();$u=wp_get_current_user();$d=self::data();Elev8_OS_Marketing_Service::save_campaign((int)$u->ID,$d,'draft');self::redirect(__('Draft saved.','elev8-os')); }
    public static function send_test(): void { self::authorize();$r=Elev8_OS_Marketing_Service::send_campaign(wp_get_current_user(),self::data(),true);self::redirect((string)$r['message']); }
    public static function send(): void { self::authorize();$r=Elev8_OS_Marketing_Service::send_campaign(wp_get_current_user(),self::data(),false);self::redirect((string)$r['message']); }
    private static function authorize(): void { if(!is_user_logged_in()){wp_die(esc_html__('Please log in.','elev8-os'));}check_admin_referer('elev8_os_marketing_action'); }
    /** @return array<string,mixed> */ private static function data(): array { $url=esc_url_raw(wp_unslash($_POST['promoted_url']??''));return ['campaign_type'=>sanitize_key($_POST['campaign_type']??'custom'),'subject'=>sanitize_text_field(wp_unslash($_POST['subject']??'')),'message'=>sanitize_textarea_field(wp_unslash($_POST['message']??'')),'audience_type'=>sanitize_key($_POST['audience_type']??'all'),'audience_value'=>sanitize_text_field(wp_unslash($_POST['audience_value']??'')),'promoted_url'=>$url,'referral_url'=>Elev8_OS_Marketing_Service::referral_url(get_current_user_id(),$url)]; }
    private static function redirect(string $message): void { wp_safe_redirect(add_query_arg('elev8_message',rawurlencode($message),Elev8_OS_Portal_Page_Manager::get_url('marketing')));exit; }
}
