<?php
if (!defined('ABSPATH')) { exit; }
final class Elev8_OS_Daily_Operations_Module {
    const SLUG='elev8-daily-operations';
    public static function init(): void {
        Elev8_OS_Daily_Operations_Service::init();
        add_action('admin_menu',[__CLASS__,'menu'],25);
        add_action('admin_enqueue_scripts',[__CLASS__,'assets']);
        add_action('admin_post_elev8_os_submit_operations_log',[__CLASS__,'submit']);
        add_action('admin_post_elev8_os_update_operations_status',[__CLASS__,'update_status']);
        add_action('admin_post_elev8_os_save_operations_template',[__CLASS__,'save_template']);
        add_action('admin_post_elev8_os_delete_operations_template',[__CLASS__,'delete_template']);
        add_shortcode('elev8_operations_log',[__CLASS__,'shortcode']);
    }
    public static function menu():void{add_submenu_page('elev8-os','Daily Operations Intelligence','Daily Operations','read',self::SLUG,[__CLASS__,'render']);}
    public static function assets(string $hook):void{if($hook!=='elev8-os_page_'.self::SLUG)return;wp_enqueue_style('elev8-daily-operations',ELEV8_OS_URL.'assets/css/daily-operations.css',[],ELEV8_OS_VERSION);}
    private static function url(array $args=[]):string{return add_query_arg(array_merge(['page'=>self::SLUG],$args),admin_url('admin.php'));}
    public static function render():void{
        if(!is_user_logged_in())wp_die('Please sign in.');
        $view=sanitize_key((string)($_GET['view']??(current_user_can('manage_options')?'brief':'submit')));
        echo '<div class="wrap elev8-ops">';self::header($view);
        if(isset($_GET['saved']))echo '<div class="notice notice-success is-dismissible"><p>Operating log saved. It is now part of the company memory.</p></div>';
        if(isset($_GET['error']))echo '<div class="notice notice-error"><p>'.esc_html(sanitize_text_field((string)$_GET['error'])).'</p></div>';
        if($view==='submit'){self::render_submit();}
        elseif($view==='entry'&&current_user_can('manage_options')){self::render_entry(absint($_GET['entry_id']??0));}
        elseif($view==='search'&&current_user_can('manage_options')){self::render_search();}
        elseif($view==='templates'&&current_user_can('manage_options')){self::render_templates();}
        elseif(current_user_can('manage_options')){self::render_brief();}
        else{self::render_submit();}
        echo '</div>';
    }
    private static function header(string $view):void{?>
        <header class="elev8-ops__header"><div><p class="elev8-ops__eyebrow">ELEV8 OS <?php echo esc_html(ELEV8_OS_VERSION);?></p><h1>Daily Operations Intelligence</h1><p>The permanent operational memory of your business.</p></div><span>Living Knowledge Base</span></header>
        <nav class="elev8-ops__nav"><a class="button <?php echo $view==='submit'?'button-primary':'';?>" href="<?php echo esc_url(self::url(['view'=>'submit']));?>">Submit a log</a><?php if(current_user_can('manage_options')):?><a class="button <?php echo $view==='brief'?'button-primary':'';?>" href="<?php echo esc_url(self::url(['view'=>'brief']));?>">Executive brief</a><a class="button <?php echo $view==='search'?'button-primary':'';?>" href="<?php echo esc_url(self::url(['view'=>'search']));?>">Search memory</a><a class="button <?php echo $view==='templates'?'button-primary':'';?>" href="<?php echo esc_url(self::url(['view'=>'templates']));?>">Templates</a><?php endif;?></nav><?php
    }
    private static function render_submit():void{
        $templates=Elev8_OS_Daily_Operations_Service::templates_for_user(get_current_user_id());$selected=sanitize_key((string)($_GET['template']??array_key_first($templates)));
        if(!$templates){echo '<div class="elev8-ops__empty">No operating log is assigned to your role.</div>';return;}
        if(!isset($templates[$selected]))$selected=array_key_first($templates);$template=$templates[$selected];?>
        <div class="elev8-ops__submit-layout"><aside class="elev8-ops__template-list"><h2>Choose a log</h2><?php foreach($templates as $key=>$item):?><a class="<?php echo $key===$selected?'is-active':'';?>" href="<?php echo esc_url(self::url(['view'=>'submit','template'=>$key]));?>"><strong><?php echo esc_html($item['name']);?></strong><small><?php echo esc_html($item['description']);?></small></a><?php endforeach;?></aside>
        <section class="elev8-ops__panel"><h2><?php echo esc_html($template['name']);?></h2><p><?php echo esc_html($template['description']);?></p><form method="post" enctype="multipart/form-data" action="<?php echo esc_url(admin_url('admin-post.php'));?>" class="elev8-ops__form"><?php wp_nonce_field('elev8_ops_submit');?><input type="hidden" name="action" value="elev8_os_submit_operations_log"><input type="hidden" name="template" value="<?php echo esc_attr($selected);?>"><div class="elev8-ops__two"><label>Entry date<input type="date" name="entry_date" value="<?php echo esc_attr(current_time('Y-m-d'));?>" required></label><label>Primary location<input type="text" name="location" placeholder="Optional location"></label></div><?php foreach($template['fields'] as $field)self::field($field);?><label class="elev8-ops__attention"><input type="checkbox" name="owner_attention" value="1"> This needs the owner's attention</label><label>Photos or attachments <small>Up to five files</small><input type="file" name="attachments[]" multiple accept="image/*,.pdf,.doc,.docx,.txt"></label><button class="button button-primary button-hero">Save operating log</button></form></section></div><?php
    }
    private static function field(array $field):void{$key=$field['key'];$req=!empty($field['required'])?' required':'';echo '<label>'.esc_html($field['label']).(!empty($field['required'])?' <b>*</b>':'');if($field['type']==='textarea')echo '<textarea name="fields['.esc_attr($key).']" rows="4"'.$req.'></textarea>';elseif($field['type']==='select'){echo '<select name="fields['.esc_attr($key).']"'.$req.'><option value="">Select</option>';foreach($field['options'] as $o)echo '<option>'.esc_html($o).'</option>';echo '</select>';}elseif($field['type']==='checkbox')echo '<input type="checkbox" name="fields['.esc_attr($key).']" value="1">';else echo '<input type="'.esc_attr(in_array($field['type'],['number','date'],true)?$field['type']:'text').'" name="fields['.esc_attr($key).']"'.$req.'>';echo '</label>';}
    public static function submit():void{if(!is_user_logged_in())wp_die('Sign in required.');check_admin_referer('elev8_ops_submit');$id=Elev8_OS_Daily_Operations_Service::save_entry(wp_unslash($_POST),$_FILES,get_current_user_id());if(is_wp_error($id)){$url=self::url(['view'=>'submit','template'=>sanitize_key((string)($_POST['template']??'')),'error'=>$id->get_error_message()]);}else{$url=self::url(['view'=>'submit','template'=>sanitize_key((string)($_POST['template']??'')),'saved'=>1]);}wp_safe_redirect($url);exit;}
    private static function render_brief():void{$date=sanitize_text_field((string)($_GET['date']??current_time('Y-m-d')));$b=Elev8_OS_Operations_Intelligence_Service::daily_brief($date);$trends=Elev8_OS_Operations_Intelligence_Service::trend_terms(30);?>
        <section class="elev8-ops__metrics"><article><strong><?php echo absint($b['entry_count']);?></strong><span>Logs today</span></article><article><strong><?php echo count($b['urgent']);?></strong><span>Urgent items</span></article><article><strong><?php echo count($b['waiting']);?></strong><span>Waiting</span></article><article><strong><?php echo count($b['completed']);?></strong><span>Completed</span></article></section>
        <form class="elev8-ops__date" method="get"><input type="hidden" name="page" value="<?php echo esc_attr(self::SLUG);?>"><input type="hidden" name="view" value="brief"><label>Brief date <input type="date" name="date" value="<?php echo esc_attr($date);?>"></label><button class="button">View</button></form>
        <div class="elev8-ops__brief-grid"><?php self::brief_card("Today's summary",$b['summary'],'No logs were submitted for this date.');self::brief_card('Urgent issues',$b['urgent'],'No urgent issues reported.','urgent');self::brief_card('Waiting items',$b['waiting'],'Nothing is waiting.');self::brief_card('Completed items',$b['completed'],'No completed items reported.');self::brief_card('Recommendations',$b['recommendations'],'More entries will produce stronger recommendations.','recommend');?><article class="elev8-ops__panel"><h2>30-day signal radar</h2><?php if(!$trends):?><p class="muted">No repeated signals yet.</p><?php else:?><div class="elev8-ops__signals"><?php foreach(array_slice($trends,0,8,true) as $term=>$count):?><span><b><?php echo absint($count);?></b> <?php echo esc_html(ucwords($term));?></span><?php endforeach;?></div><?php endif;?></article></div>
        <section class="elev8-ops__panel"><div class="elev8-ops__panel-head"><div><h2>Latest operational memory</h2><p>Open any record to review the structured details.</p></div><a class="button" href="<?php echo esc_url(self::url(['view'=>'search']));?>">Search everything</a></div><?php self::entry_table(Elev8_OS_Daily_Operations_Service::entries(['posts_per_page'=>10])['items']);?></section><?php
    }
    private static function brief_card(string $title,array $items,string $empty,string $class=''):void{echo '<article class="elev8-ops__panel '.esc_attr($class).'"><h2>'.esc_html($title).'</h2>';if(!$items)echo '<p class="muted">'.esc_html($empty).'</p>';else{echo '<ul>';foreach($items as $i)echo '<li>'.esc_html($i).'</li>';echo '</ul>';}echo '</article>';}
    private static function render_search():void{$args=['s'=>sanitize_text_field((string)($_GET['q']??'')),'status'=>sanitize_key((string)($_GET['status']??'')),'template'=>sanitize_key((string)($_GET['template']??'')),'attention'=>isset($_GET['attention'])?'1':''];$r=Elev8_OS_Daily_Operations_Service::entries($args);?>
        <section class="elev8-ops__panel"><h2>Search operational memory</h2><form method="get" class="elev8-ops__filters"><input type="hidden" name="page" value="<?php echo esc_attr(self::SLUG);?>"><input type="hidden" name="view" value="search"><input type="search" name="q" value="<?php echo esc_attr($args['s']);?>" placeholder="parking, checkout, Nicole, inventory..."><select name="template"><option value="">All report types</option><?php foreach(Elev8_OS_Daily_Operations_Service::templates() as $key=>$t):?><option value="<?php echo esc_attr($key);?>" <?php selected($args['template'],$key);?>><?php echo esc_html($t['name']);?></option><?php endforeach;?></select><select name="status"><option value="">All statuses</option><?php foreach(['new','reviewed','waiting','completed'] as $s):?><option value="<?php echo esc_attr($s);?>" <?php selected($args['status'],$s);?>><?php echo esc_html(ucfirst($s));?></option><?php endforeach;?></select><label><input type="checkbox" name="attention" value="1" <?php checked($args['attention'],'1');?>> Owner attention</label><button class="button button-primary">Search</button></form><p><strong><?php echo absint($r['total']);?></strong> matching records</p><?php self::entry_table($r['items']);?></section><?php
    }
    private static function entry_table(array $posts):void{if(!$posts){echo '<div class="elev8-ops__empty">No matching operating logs.</div>';return;}echo '<div class="elev8-ops__table"><table><thead><tr><th>Date</th><th>Report</th><th>Person</th><th>Location</th><th>Status</th><th></th></tr></thead><tbody>';foreach($posts as $p){$e=Elev8_OS_Daily_Operations_Service::entry((int)$p->ID);$t=Elev8_OS_Daily_Operations_Service::template($e['template_key']);echo '<tr><td>'.esc_html($e['entry_date']).'</td><td><strong>'.esc_html($t['name']??'Operating Log').'</strong>'.($e['attention']?'<em>Owner attention</em>':'').'</td><td>'.esc_html(get_the_author_meta('display_name',(int)$p->post_author)).'</td><td>'.esc_html($e['location']?:'—').'</td><td><span class="status status-'.esc_attr($e['status']).'">'.esc_html(ucfirst($e['status'])).'</span></td><td><a class="button button-small" href="'.esc_url(self::url(['view'=>'entry','entry_id'=>$p->ID])).'">Open</a></td></tr>';}echo '</tbody></table></div>';}
    private static function render_entry(int $id):void{$e=Elev8_OS_Daily_Operations_Service::entry($id);if(!$e){echo '<div class="notice notice-error"><p>Operating log not found.</p></div>';return;}$t=Elev8_OS_Daily_Operations_Service::template($e['template_key']);?>
        <p><a href="<?php echo esc_url(self::url(['view'=>'search']));?>">← Back to operational memory</a></p><div class="elev8-ops__entry-head"><div><p class="elev8-ops__eyebrow"><?php echo esc_html($t['name']??'Operating Log');?></p><h2><?php echo esc_html($e['post']->post_title);?></h2><p><?php echo esc_html($e['entry_date'].' · '.get_the_author_meta('display_name',(int)$e['post']->post_author).($e['location']?' · '.$e['location']:''));?></p></div><?php if($e['attention']):?><span class="attention-pill">Owner attention</span><?php endif;?></div><div class="elev8-ops__entry-layout"><section class="elev8-ops__panel"><h2>Structured report</h2><dl class="elev8-ops__details"><?php foreach($t['fields'] as $f):$v=$e['fields'][$f['key']]??'';if($v==='')continue;?><div><dt><?php echo esc_html($f['label']);?></dt><dd><?php echo nl2br(esc_html($v));?></dd></div><?php endforeach;?></dl><?php if($e['attachments']):?><h3>Attachments</h3><div class="elev8-ops__attachments"><?php foreach($e['attachments'] as $aid):$url=wp_get_attachment_url((int)$aid);if(!$url)continue;?><a href="<?php echo esc_url($url);?>" target="_blank"><?php echo wp_get_attachment_image((int)$aid,'thumbnail')?:esc_html(get_the_title((int)$aid));?></a><?php endforeach;?></div><?php endif;?></section><aside class="elev8-ops__panel"><h2>Owner workflow</h2><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><?php wp_nonce_field('elev8_ops_status_'.$id);?><input type="hidden" name="action" value="elev8_os_update_operations_status"><input type="hidden" name="entry_id" value="<?php echo absint($id);?>"><label>Status<select name="status"><?php foreach(['new','reviewed','waiting','completed'] as $s):?><option value="<?php echo esc_attr($s);?>" <?php selected($e['status'],$s);?>><?php echo esc_html(ucfirst($s));?></option><?php endforeach;?></select></label><button class="button button-primary">Update status</button></form></aside></div><?php
    }
    public static function update_status():void{if(!current_user_can('manage_options'))wp_die('Not allowed.');$id=absint($_POST['entry_id']??0);check_admin_referer('elev8_ops_status_'.$id);Elev8_OS_Daily_Operations_Service::update_status($id,sanitize_key((string)($_POST['status']??'')));wp_safe_redirect(self::url(['view'=>'entry','entry_id'=>$id,'saved'=>1]));exit;}
    private static function render_templates():void{$templates=Elev8_OS_Daily_Operations_Service::templates();?>
        <div class="elev8-ops__template-admin"><section class="elev8-ops__panel"><h2>Report templates</h2><p>Templates define the questions without hardcoding submission forms.</p><?php foreach($templates as $key=>$t):?><article class="elev8-ops__template-row"><div><strong><?php echo esc_html($t['name']);?></strong><small><?php echo count($t['fields']);?> fields · <?php echo !empty($t['custom'])?'Custom':'Elev8 default';?></small></div><?php if(!empty($t['custom'])):?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>" onsubmit="return confirm('Delete this custom template?');"><?php wp_nonce_field('elev8_ops_delete_template_'.$key);?><input type="hidden" name="action" value="elev8_os_delete_operations_template"><input type="hidden" name="template" value="<?php echo esc_attr($key);?>"><button class="button button-link-delete">Delete</button></form><?php endif;?></article><?php endforeach;?></section><section class="elev8-ops__panel"><h2>Create a template</h2><p>Create a reusable role-based form. Add up to eight fields now; the service supports more programmatically.</p><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>" class="elev8-ops__form"><?php wp_nonce_field('elev8_ops_save_template');?><input type="hidden" name="action" value="elev8_os_save_operations_template"><label>Template name<input name="name" required></label><label>Description<textarea name="description" rows="3"></textarea></label><label>Available to roles<select name="roles[]" multiple size="6"><?php foreach(wp_roles()->roles as $key=>$role):?><option value="<?php echo esc_attr($key);?>"><?php echo esc_html($role['name']);?></option><?php endforeach;?></select></label><h3>Fields</h3><?php for($i=0;$i<8;$i++):?><div class="elev8-ops__field-builder"><input name="field_label[]" placeholder="Field label"><select name="field_type[]"><option value="textarea">Long answer</option><option value="text">Short answer</option><option value="number">Number</option><option value="date">Date</option><option value="checkbox">Checkbox</option></select><label><input type="checkbox" name="field_required[<?php echo $i;?>]" value="1"> Required</label></div><?php endfor;?><button class="button button-primary">Create template</button></form></section></div><?php
    }
    public static function save_template():void{if(!current_user_can('manage_options'))wp_die('Not allowed.');check_admin_referer('elev8_ops_save_template');$fields=[];$labels=(array)($_POST['field_label']??[]);$types=(array)($_POST['field_type']??[]);foreach($labels as $i=>$label){if(trim((string)$label)==='')continue;$fields[]=['label'=>wp_unslash($label),'type'=>sanitize_key((string)($types[$i]??'textarea')),'required'=>!empty($_POST['field_required'][$i])];}Elev8_OS_Daily_Operations_Service::save_template(['name'=>wp_unslash($_POST['name']??''),'description'=>wp_unslash($_POST['description']??''),'roles'=>(array)($_POST['roles']??[]),'fields'=>$fields]);wp_safe_redirect(self::url(['view'=>'templates','saved'=>1]));exit;}
    public static function delete_template():void{if(!current_user_can('manage_options'))wp_die('Not allowed.');$key=sanitize_key((string)($_POST['template']??''));check_admin_referer('elev8_ops_delete_template_'.$key);Elev8_OS_Daily_Operations_Service::delete_template($key);wp_safe_redirect(self::url(['view'=>'templates']));exit;}
    public static function shortcode():string{if(!is_user_logged_in())return '<p>Please sign in to submit an operating log.</p>';ob_start();self::render_submit();return (string)ob_get_clean();}
}
