<?php
if (!defined('ABSPATH')) { exit; }
final class Elev8_OS_Gallery_Operations_Module {
    public static function init(): void {
        add_action('admin_menu',[__CLASS__,'menu'],20); add_action('admin_enqueue_scripts',[__CLASS__,'assets']);
        add_action('admin_post_elev8_os_save_gallery_zone',[__CLASS__,'save_zone']); add_action('admin_post_elev8_os_create_portal_rack',[__CLASS__,'create_rack']); add_action('admin_post_elev8_os_place_asset',[__CLASS__,'place']); add_action('admin_post_elev8_os_remove_asset_display',[__CLASS__,'remove']);
        add_shortcode('elev8_artist_gallery_status',[__CLASS__,'artist_status']);
    }
    public static function menu(): void { add_submenu_page('elev8-os','Gallery Operations','Gallery Operations','manage_options','elev8-gallery-operations',[__CLASS__,'render']); }
    public static function assets(string $hook): void { if($hook!=='elev8-os_page_elev8-gallery-operations') return; wp_enqueue_style('elev8-gallery-operations',ELEV8_OS_URL.'assets/css/gallery-operations.css',[],ELEV8_OS_VERSION); }
    public static function render(): void {
        if(!current_user_can('manage_options')) wp_die('Not allowed.');
        $artist_filter=absint($_GET['artist_filter']??0); $view=sanitize_key((string)($_GET['view']??'dashboard')); $search=sanitize_text_field((string)($_GET['art_search']??''));
        $d=Elev8_OS_Gallery_Operations_Service::dashboard($artist_filter,$search); $zones=$d['zones']; $notice=sanitize_text_field((string)($_GET['gallery_notice']??'')); ?>
        <div class="wrap elev8-gallery-ops"><header class="elev8-go-header"><div><p class="eyebrow">ELEV8 OS 9.0.2</p><h1>Gallery Operations</h1><p>Place, move, store, and find every artwork from one screen.</p></div><span class="mode-pill">Gallery Mode</span></header>
        <?php if($notice):?><div class="notice notice-success is-dismissible"><p><?php echo esc_html($notice);?></p></div><?php endif;?>
        <nav class="go-view-nav"><a class="button <?php echo $view!=='all'?'button-primary':'';?>" href="<?php echo esc_url(self::url(['view'=>'dashboard','artist_filter'=>$artist_filter]));?>">Gallery overview</a><a class="button <?php echo $view==='all'?'button-primary':'';?>" href="<?php echo esc_url(self::url(['view'=>'all','artist_filter'=>$artist_filter]));?>">See all artwork</a></nav>
        <form method="get" class="go-artist-filter"><input type="hidden" name="page" value="elev8-gallery-operations"><input type="hidden" name="view" value="<?php echo esc_attr($view);?>"><label for="artist_filter"><strong>Filter by artist</strong></label><select id="artist_filter" name="artist_filter" onchange="this.form.submit()"><option value="0">All artists</option><?php foreach($d['artists'] as $artist):?><option value="<?php echo absint($artist['ID']);?>" <?php selected($artist_filter,absint($artist['ID']));?>><?php echo esc_html($artist['display_name'].' — '.$artist['user_email']);?></option><?php endforeach;?></select><?php if($artist_filter):?><a class="button" href="<?php echo esc_url(self::url(['view'=>$view]));?>">Clear filter</a><?php endif;?></form>
        <?php if($view==='all'){ self::render_all($d,$zones,$artist_filter,$search); echo '</div>'; return; } ?>
        <section class="go-kpis"><?php foreach([['Available',$d['summary']['available']??0],['Reserved',$d['summary']['reserved']??0],['On display',count($d['placed'])],['Available value','$'.number_format_i18n((float)($d['summary']['available_value']??0),2)],['Needs placement',count($d['unplaced'])]] as $k):?><article><strong><?php echo esc_html((string)$k[1]);?></strong><span><?php echo esc_html($k[0]);?></span></article><?php endforeach;?></section>
        <section class="go-grid"><article class="go-card go-wide"><h2>Gallery floor</h2><p>Current display zones and capacity.</p><div class="zone-grid"><?php foreach($zones as $z):?><div class="zone <?php echo $z['zone_type']==='artist_portal_rack'?'portal-zone':'';?>"><div><strong><?php echo esc_html($z['name']);?></strong><small><?php echo esc_html(self::zone_type_label($z));?></small></div><b><?php echo absint($z['piece_count']);?><?php echo absint($z['capacity'])?' / '.absint($z['capacity']):'';?></b><span><?php echo esc_html(ucfirst((string)($z['board_status']??'available')));?> · <?php echo esc_html('$'.number_format_i18n((float)$z['display_value'],2));?> displayed</span></div><?php endforeach;?></div></article>
        <article class="go-card"><h2>Add display zone</h2><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>" class="stack"><?php wp_nonce_field('elev8_save_gallery_zone');?><input type="hidden" name="action" value="elev8_os_save_gallery_zone"><label>Name<input required name="name" placeholder="North Wall"></label><label>Type<select name="zone_type"><option value="wall">Wall</option><option value="window">Window</option><option value="case">Case</option><option value="display">Display</option><option value="room">Room</option><option value="storage">Storage</option></select></label><label>Capacity<input type="number" min="0" name="capacity"></label><input type="hidden" name="active" value="1"><button class="button button-primary">Add zone</button></form></article></section>
        <section class="go-card portal-rack-setup"><h2>Artist Portal racks</h2><p>Each physical rack has numbered board positions. Create Rack 1 and Rack 2 with 40 boards each.</p><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>" class="rack-form"><?php wp_nonce_field('elev8_create_portal_rack');?><input type="hidden" name="action" value="elev8_os_create_portal_rack"><label>Rack number<input required type="number" min="1" max="99" name="rack_number" value="1"></label><label>Number of board positions<input required type="number" min="1" max="100" name="board_count" value="40"></label><label>Artwork capacity per board<input required type="number" min="1" max="20" name="capacity_per_board" value="1"></label><button class="button button-primary">Create or update rack</button></form><p class="description">Example: Artist Portal Rack 2 → Board 17. No A/B sides are used.</p></section>
        <section class="go-grid"><article class="go-card"><h2>Needs placement</h2><p>Artwork at Elev8 without a display or storage location.</p><?php if(!$d['unplaced']):?><div class="empty">No matching artwork needs placement.</div><?php else:?><div class="asset-list"><?php foreach($d['unplaced'] as $a): self::asset_form($a,$zones,false,$artist_filter); endforeach;?></div><?php endif;?></article>
        <article class="go-card"><h2>On display</h2><p>Change a location or move a piece to storage.</p><?php if(!$d['placed']):?><div class="empty">No matching artwork is currently displayed.</div><?php else:?><div class="asset-list"><?php foreach($d['placed'] as $a): self::asset_form($a,$zones,true,$artist_filter); endforeach;?></div><?php endif;?></article></section>
        <section class="go-card"><h2>Morning gallery brief</h2><div class="brief"><p><strong><?php echo count($d['unplaced']);?></strong> pieces need placement.</p><p><strong><?php echo absint($d['summary']['reserved']??0);?></strong> pieces are reserved.</p><p><strong><?php echo count(array_filter($zones,fn($z)=>absint($z['capacity'])>0 && absint($z['piece_count'])<absint($z['capacity'])));?></strong> zones have open capacity.</p></div></section></div><?php
    }
    private static function render_all(array $d,array $zones,int $artist_filter,string $search): void { ?>
        <section class="go-card all-artwork-card"><div class="go-card-head"><div><h2>All artwork locations</h2><p>Search any artwork, see its current location, and change it without recreating the record.</p></div></div><form method="get" class="all-art-search"><input type="hidden" name="page" value="elev8-gallery-operations"><input type="hidden" name="view" value="all"><input type="hidden" name="artist_filter" value="<?php echo absint($artist_filter);?>"><input type="search" name="art_search" value="<?php echo esc_attr($search);?>" placeholder="Search title, artist, or email"><button class="button">Search</button><?php if($search):?><a class="button" href="<?php echo esc_url(self::url(['view'=>'all','artist_filter'=>$artist_filter]));?>">Clear search</a><?php endif;?></form>
        <?php if(!$d['all']):?><div class="empty">No matching artwork found.</div><?php else:?><div class="all-artwork-list"><?php foreach($d['all'] as $a):?><article class="all-art-row"><div class="art-summary"><strong><?php echo esc_html($a['title']);?></strong><span><?php echo esc_html(($a['artist_name']?:$a['artist_email']).' · '.ucfirst((string)$a['status']));?></span><b><?php echo esc_html($a['zone_name']?:'No location');?><?php if(!empty($a['placement_status']) && $a['placement_status']!=='displayed') echo ' · '.esc_html(ucfirst($a['placement_status']));?></b></div><?php self::location_controls($a,$zones,$artist_filter);?><details><summary>Placement history</summary><?php $history=Elev8_OS_Gallery_Operations_Service::get_history(absint($a['id']),10); if(!$history):?><p>No movement history yet.</p><?php else:?><ul class="history-list"><?php foreach($history as $h):?><li><strong><?php echo esc_html(ucfirst(str_replace('_',' ',$h['event_type'])));?></strong> <?php echo esc_html(($h['from_zone']?:'No location').' → '.($h['to_zone']?:'No location'));?> <small><?php echo esc_html(mysql2date('M j, Y g:i a',$h['created_at']));?></small></li><?php endforeach;?></ul><?php endif;?></details></article><?php endforeach;?></div><?php endif;?></section><?php
    }
    private static function zone_type_label(array $z): string { if(($z['zone_type']??'')==='artist_portal_rack') return sprintf('Artist Portal Rack %d · Board %d',absint($z['rack_number']),absint($z['board_number'])); return ucfirst(str_replace('_',' ',(string)($z['zone_type']??'display'))); }
    private static function asset_form(array $a,array $zones,bool $placed=false,int $artist_filter=0): void { ?><div class="asset-row"><div><strong><?php echo esc_html($a['title']);?></strong><small><?php echo esc_html((string)($a['artist_name']??get_the_author_meta('display_name',absint($a['owner_user_id']))));?> · <?php echo esc_html(ucfirst($a['status']));?><?php if(!empty($a['zone_name'])) echo ' · '.esc_html($a['zone_name']);?></small></div><?php self::location_controls($a,$zones,$artist_filter,$placed);?></div><?php }
    private static function location_controls(array $a,array $zones,int $artist_filter=0,bool $placed=true): void { ?>
        <div class="location-controls"><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><?php wp_nonce_field('elev8_place_asset_'.$a['id']);?><input type="hidden" name="action" value="elev8_os_place_asset"><input type="hidden" name="asset_id" value="<?php echo absint($a['id']);?>"><input type="hidden" name="artist_filter" value="<?php echo absint($artist_filter);?>"><input type="hidden" name="return_view" value="<?php echo esc_attr(sanitize_key((string)($_GET['view']??'dashboard')));?>"><select name="zone_id" required><option value="">Choose new location</option><?php foreach($zones as $z): $assigned=absint($z['assigned_artist_user_id']??0); $wrong=$assigned && $assigned!==absint($a['owner_user_id']);?><option value="<?php echo absint($z['id']);?>" <?php selected(absint($a['zone_id']??0),absint($z['id']));?> <?php disabled($wrong || ($z['board_status']??'')==='maintenance');?>><?php echo esc_html($z['name'].($wrong?' — reserved':''));?></option><?php endforeach;?></select><input name="position_label" value="<?php echo esc_attr((string)($a['position_label']??''));?>" placeholder="Optional shelf / note"><button class="button button-primary"><?php echo $placed?'Change location':'Place artwork';?></button></form>
        <?php if($placed || !empty($a['placement_status'])):?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><?php wp_nonce_field('elev8_remove_asset_'.$a['id']);?><input type="hidden" name="action" value="elev8_os_remove_asset_display"><input type="hidden" name="asset_id" value="<?php echo absint($a['id']);?>"><input type="hidden" name="artist_filter" value="<?php echo absint($artist_filter);?>"><input type="hidden" name="return_view" value="<?php echo esc_attr(sanitize_key((string)($_GET['view']??'dashboard')));?>"><select name="placement_status"><option value="storage">Move to storage</option><option value="pickup">Needs pickup</option><option value="removed">Remove location</option></select><button class="button">Update storage/status</button></form><?php endif;?></div><?php
    }
    public static function save_zone(): void { self::guard(); check_admin_referer('elev8_save_gallery_zone'); $r=Elev8_OS_Gallery_Operations_Service::save_zone($_POST); self::redirect(is_wp_error($r)?$r->get_error_message():'Display zone added.'); }
    public static function create_rack(): void { self::guard(); check_admin_referer('elev8_create_portal_rack'); $r=Elev8_OS_Gallery_Operations_Service::create_artist_portal_rack(absint($_POST['rack_number']??0),absint($_POST['board_count']??40),absint($_POST['capacity_per_board']??1)); self::redirect(is_wp_error($r)?$r->get_error_message():sprintf('%d Artist Portal board positions are ready.',absint($r))); }
    public static function place(): void { self::guard(); $id=absint($_POST['asset_id']??0); check_admin_referer('elev8_place_asset_'.$id); $r=Elev8_OS_Gallery_Operations_Service::place_asset($id,absint($_POST['zone_id']??0),wp_unslash($_POST['position_label']??'')); self::redirect(is_wp_error($r)?$r->get_error_message():'Artwork location updated.'); }
    public static function remove(): void { self::guard(); $id=absint($_POST['asset_id']??0); check_admin_referer('elev8_remove_asset_'.$id); $r=Elev8_OS_Gallery_Operations_Service::remove_from_display($id,sanitize_key($_POST['placement_status']??'removed')); self::redirect(is_wp_error($r)?$r->get_error_message():'Artwork storage/status updated.'); }
    private static function guard(): void { if(!current_user_can('manage_options')) wp_die('Not allowed.'); }
    private static function url(array $args=[]): string { return add_query_arg(array_filter(array_merge(['page'=>'elev8-gallery-operations'],$args),fn($v)=>$v!==''&&$v!==0),admin_url('admin.php')); }
    private static function redirect(string $m): void { $args=['gallery_notice'=>$m,'view'=>sanitize_key((string)($_POST['return_view']??'dashboard'))]; if(!empty($_POST['artist_filter'])) $args['artist_filter']=absint($_POST['artist_filter']); wp_safe_redirect(self::url($args)); exit; }
    public static function artist_status(): string { if(!is_user_logged_in()) return ''; $s=Elev8_OS_Gallery_Operations_Service::owner_snapshot(get_current_user_id()); ob_start();?><section class="elev8-artist-gallery-status"><h2>Where is my artwork?</h2><?php if(!$s['rows']):?><p>No artwork records yet.</p><?php else:?><div class="elev8-table-wrap"><table><thead><tr><th>Artwork</th><th>Status</th><th>Location</th><th>Days displayed</th></tr></thead><tbody><?php foreach($s['rows'] as $r):?><tr><td><?php echo esc_html($r['title']);?></td><td><?php echo esc_html(ucfirst($r['status']));?></td><td><?php echo esc_html($r['zone_name']?:'Not currently displayed');?></td><td><?php echo $r['days_displayed']!==null?absint($r['days_displayed']):'—';?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section><?php return (string)ob_get_clean(); }
}
