<?php
if (!defined('ABSPATH')) { exit; }

final class Elev8_OS_Production_Catalog_Module {
    const SLUG='elev8-production-catalog';

    public static function init(): void {
        Elev8_OS_Production_Catalog_Service::init();
        add_action('admin_menu',[__CLASS__,'menu'],19);
        add_action('admin_enqueue_scripts',[__CLASS__,'assets']);
        add_action('admin_post_elev8_os_save_production_product',[__CLASS__,'save_product']);
        add_action('admin_post_elev8_os_save_production_material',[__CLASS__,'save_material']);
        add_action('admin_post_elev8_os_save_compensation_profile',[__CLASS__,'save_profile']);
    }

    public static function menu(): void {
        add_submenu_page('elev8-os','Production Catalog','Production Catalog','read',self::SLUG,[__CLASS__,'render']);
    }

    public static function assets(string $hook): void {
        if(strpos($hook,self::SLUG)===false)return;
        wp_enqueue_style('elev8-production-catalog',ELEV8_OS_URL.'assets/css/production-catalog.css',[],ELEV8_OS_VERSION);
    }

    private static function can_manage(): bool {
        return Elev8_OS_Access_Service::user_can('manage_glass_production') || current_user_can('manage_options');
    }
    private static function guard(): void { if(!self::can_manage())wp_die('You do not have permission to manage the Production Catalog.'); }
    private static function url(array $args=[]): string { return add_query_arg(array_merge(['page'=>self::SLUG],$args),admin_url('admin.php')); }

    public static function render(): void {
        self::guard();
        $view=sanitize_key($_GET['view']??'products');
        ?><div class="wrap elev8-production"><header class="elev8-production__hero"><div><p class="eyebrow">Production Engine</p><h1>Glass Production Catalog</h1><p>Define what can be made, what it costs, and whether each operation is hourly, piecework, either, or included.</p></div><nav><a class="button <?php echo $view==='products'?'button-primary':'';?>" href="<?php echo esc_url(self::url());?>">Products</a><a class="button <?php echo $view==='new-product'?'button-primary':'';?>" href="<?php echo esc_url(self::url(['view'=>'new-product']));?>">New product</a><a class="button <?php echo $view==='materials'?'button-primary':'';?>" href="<?php echo esc_url(self::url(['view'=>'materials']));?>">Materials</a><a class="button <?php echo $view==='compensation'?'button-primary':'';?>" href="<?php echo esc_url(self::url(['view'=>'compensation']));?>">Compensation profiles</a></nav></header><?php
        if(!empty($_GET['notice']))echo '<div class="notice notice-success is-dismissible"><p>'.esc_html(wp_unslash($_GET['notice'])).'</p></div>';
        if($view==='new-product'||$view==='edit-product')self::product_form(absint($_GET['product_id']??0));
        elseif($view==='materials')self::materials();
        elseif($view==='compensation')self::compensation();
        else self::products();
        ?></div><?php
    }

    private static function products(): void {
        $products=Elev8_OS_Production_Catalog_Service::products(['search'=>sanitize_text_field($_GET['s']??''),'active'=>isset($_GET['active'])?sanitize_text_field($_GET['active']):'']);
        ?><section class="panel"><div class="panel-head"><div><h2>Production products</h2><p>This is a new Elev8 OS catalog. Nothing is imported from the spreadsheet automatically.</p></div><a class="button button-primary" href="<?php echo esc_url(self::url(['view'=>'new-product']));?>">Create production product</a></div><form class="catalog-filters"><input type="hidden" name="page" value="<?php echo esc_attr(self::SLUG);?>"><input type="search" name="s" value="<?php echo esc_attr($_GET['s']??'');?>" placeholder="Search name, code or category"><select name="active"><option value="">All status</option><option value="1" <?php selected($_GET['active']??'','1');?>>Active</option><option value="0" <?php selected($_GET['active']??'','0');?>>Inactive</option></select><button class="button">Filter</button></form><?php if(!$products){echo '<div class="empty">No production products yet. Create the first item manually from your production rules.</div>';}else{?><div class="table-wrap"><table><thead><tr><th>Product</th><th>Category</th><th>Compensation</th><th>Estimated time</th><th>Estimated cost</th><th>Version</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($products as $p):$p['materials']=Elev8_OS_Production_Catalog_Service::product_materials((int)$p['id']);$cost=Elev8_OS_Production_Catalog_Service::cost_summary($p);?><tr><td><strong><?php echo esc_html($p['product_name']);?></strong><small><?php echo esc_html($p['product_code']);?></small></td><td><?php echo esc_html($p['category']?:'Uncategorized');?></td><td><span class="pill"><?php echo esc_html(ucfirst($p['compensation_method']));?></span><?php if(in_array($p['compensation_method'],['piecework','either'],true)):?><small>$<?php echo number_format_i18n((float)$p['piecework_rate'],2);?> / <?php echo esc_html($p['piecework_unit']);?></small><?php endif;?></td><td><?php echo $p['estimated_minutes']>0?esc_html($p['estimated_minutes'].' min'):'Unavailable';?></td><td><strong>$<?php echo number_format_i18n($cost['total'],2);?></strong></td><td>v<?php echo absint($p['version_number']);?></td><td><?php echo $p['active']?'Active':'Inactive';?></td><td><a class="button button-small" href="<?php echo esc_url(self::url(['view'=>'edit-product','product_id'=>$p['id']]));?>">Edit</a></td></tr><?php endforeach;?></tbody></table></div><?php }?></section><?php
    }

    private static function product_form(int $id): void {
        $p=$id?Elev8_OS_Production_Catalog_Service::product($id):null;
        $materials=Elev8_OS_Production_Catalog_Service::materials();
        $rows=$p['materials']??[]; while(count($rows)<6)$rows[]=[];
        ?><p><a href="<?php echo esc_url(self::url());?>">← Back to Production Catalog</a></p><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><?php wp_nonce_field('elev8_save_production_product');?><input type="hidden" name="action" value="elev8_os_save_production_product"><input type="hidden" name="product_id" value="<?php echo absint($id);?>"><section class="panel"><div class="panel-head"><div><h2><?php echo $id?'Edit production product':'Create production product';?></h2><p>Changes create a new version so future jobs can preserve historical payout and cost rules.</p></div><?php if($p):?><span class="version-badge">Version <?php echo absint($p['version_number']);?></span><?php endif;?></div><div class="form-grid"><label>Product name<input name="product_name" required value="<?php echo esc_attr($p['product_name']??'');?>"></label><label>Production code<input name="product_code" value="<?php echo esc_attr($p['product_code']??'');?>" placeholder="KNOB-BLACK"></label><label>Category<input name="category" value="<?php echo esc_attr($p['category']??'');?>" placeholder="Knobs, pulls, cremation, repairs"></label><label>Department<input name="department" value="<?php echo esc_attr($p['department']??'');?>" placeholder="Hot shop, cold work, shipping"></label><label>Skill level<select name="skill_level"><?php foreach(['entry'=>'Entry','standard'=>'Standard','advanced'=>'Advanced','master'=>'Master'] as $v=>$l):?><option value="<?php echo esc_attr($v);?>" <?php selected($p['skill_level']??'standard',$v);?>><?php echo esc_html($l);?></option><?php endforeach;?></select></label><label>Effective date<input type="date" name="effective_date" value="<?php echo esc_attr($p['effective_date']??current_time('Y-m-d'));?>"></label><label class="span-2">Description<textarea name="description" rows="3"><?php echo esc_textarea($p['description']??'');?></textarea></label><label class="check"><input type="checkbox" name="active" value="1" <?php checked((int)($p['active']??1),1);?>> Active production product</label></div></section>
        <section class="panel"><h2>Compensation rule</h2><p>The production product—not the employee tab—determines whether this specific work is hourly or piecework.</p><div class="comp-grid"><?php foreach(['hourly'=>'Hourly','piecework'=>'Piecework','either'=>'Either — manager chooses on job','included'=>'Included in another production item'] as $v=>$l):?><label class="choice"><input type="radio" name="compensation_method" value="<?php echo esc_attr($v);?>" <?php checked($p['compensation_method']??'hourly',$v);?>><strong><?php echo esc_html($l);?></strong></label><?php endforeach;?></div><div class="form-grid"><label>Piecework payout ($)<input type="number" step="0.01" min="0" name="piecework_rate" value="<?php echo esc_attr($p['piecework_rate']??0);?>"></label><label>Paid per<select name="piecework_unit"><?php foreach(['piece','pair','set','batch','job'] as $u):?><option value="<?php echo esc_attr($u);?>" <?php selected($p['piecework_unit']??'piece',$u);?>><?php echo esc_html(ucfirst($u));?></option><?php endforeach;?></select></label><label>Estimated production minutes<input type="number" step="0.1" min="0" name="estimated_minutes" value="<?php echo esc_attr($p['estimated_minutes']??0);?>"></label><label>Hourly costing rate ($)<input type="number" step="0.01" min="0" name="costing_hourly_rate" value="<?php echo esc_attr($p['costing_hourly_rate']??18);?>"><small>Used only for estimated costing. Actual future job pay will use the blower’s compensation profile.</small></label><label class="check"><input type="checkbox" name="manager_approval_required" value="1" <?php checked((int)($p['manager_approval_required']??1),1);?>> Manager approval required before payroll</label></div></section>
        <section class="panel"><h2>Materials and direct costs</h2><p>Material costs are definitions for future job snapshots. Update costs here without changing completed-job history.</p><div class="bom-table"><div class="bom-row bom-head"><span>Material</span><span>Quantity</span><span>Waste %</span><span>Notes</span></div><?php foreach($rows as $i=>$r):?><div class="bom-row"><select name="materials[<?php echo $i;?>][material_id]"><option value="0">Choose material</option><?php foreach($materials as $m):?><option value="<?php echo absint($m['id']);?>" <?php selected(absint($r['material_id']??0),$m['id']);?>><?php echo esc_html($m['material_name'].' — $'.number_format_i18n((float)$m['unit_cost'],4).'/'.$m['unit']);?></option><?php endforeach;?></select><input type="number" step="0.0001" min="0" name="materials[<?php echo $i;?>][quantity]" value="<?php echo esc_attr($r['quantity']??'');?>"><input type="number" step="0.01" min="0" name="materials[<?php echo $i;?>][waste_percent]" value="<?php echo esc_attr($r['waste_percent']??0);?>"><input name="materials[<?php echo $i;?>][notes]" value="<?php echo esc_attr($r['notes']??'');?>"></div><?php endforeach;?></div><div class="form-grid cost-extras"><label>Consumables ($)<input type="number" step="0.01" min="0" name="consumable_cost" value="<?php echo esc_attr($p['consumable_cost']??0);?>"></label><label>Packaging ($)<input type="number" step="0.01" min="0" name="packaging_cost" value="<?php echo esc_attr($p['packaging_cost']??0);?>"></label><label>Other direct cost ($)<input type="number" step="0.01" min="0" name="other_cost" value="<?php echo esc_attr($p['other_cost']??0);?>"></label></div></section><p><button class="button button-primary button-hero">Save production product and create version</button></p></form><?php
    }

    private static function materials(): void {
        $materials=Elev8_OS_Production_Catalog_Service::materials();
        ?><div class="elev8-production__columns"><section class="panel"><h2>Add or update material</h2><form class="stack" method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><?php wp_nonce_field('elev8_save_production_material');?><input type="hidden" name="action" value="elev8_os_save_production_material"><label>Material name<input name="material_name" required></label><label>Material code<input name="material_code" placeholder="GLASS-CLEAR"></label><label>Unit<input name="unit" value="gram" placeholder="gram, rod, foot, each"></label><label>Unit cost ($)<input type="number" step="0.0001" min="0" name="unit_cost" value="0"></label><label>Notes<textarea name="notes" rows="3"></textarea></label><label class="check"><input type="checkbox" name="active" value="1" checked> Active</label><button class="button button-primary">Save material</button></form></section><section class="panel panel-wide"><h2>Material catalog</h2><?php if(!$materials){echo '<div class="empty">No materials yet.</div>';}else{?><div class="table-wrap"><table><thead><tr><th>Material</th><th>Code</th><th>Unit</th><th>Unit cost</th><th>Status</th></tr></thead><tbody><?php foreach($materials as $m):?><tr><td><strong><?php echo esc_html($m['material_name']);?></strong></td><td><?php echo esc_html($m['material_code']);?></td><td><?php echo esc_html($m['unit']);?></td><td>$<?php echo number_format_i18n((float)$m['unit_cost'],4);?></td><td><?php echo $m['active']?'Active':'Inactive';?></td></tr><?php endforeach;?></tbody></table></div><?php }?></section></div><?php
    }

    private static function compensation(): void {
        $profiles=Elev8_OS_Production_Catalog_Service::compensation_profiles();$workers=Elev8_OS_Production_Catalog_Service::glass_workers();
        ?><div class="elev8-production__columns"><section class="panel"><h2>Glassblower compensation profile</h2><p>A blower may be hourly and still earn piecework for products explicitly marked piecework.</p><form class="stack" method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><?php wp_nonce_field('elev8_save_compensation_profile');?><input type="hidden" name="action" value="elev8_os_save_compensation_profile"><label>Glassblower<select name="user_id" required><option value="">Choose person</option><?php foreach($workers as $u):?><option value="<?php echo absint($u->ID);?>"><?php echo esc_html($u->display_name);?></option><?php endforeach;?></select></label><label>Hourly rate ($)<input type="number" step="0.01" min="0" name="hourly_rate" value="18"></label><label>Effective date<input type="date" name="effective_date" value="<?php echo esc_attr(current_time('Y-m-d'));?>"></label><label class="check"><input type="checkbox" name="piecework_eligible" value="1" checked> Eligible for product-specific piecework</label><label class="check"><input type="checkbox" name="active" value="1" checked> Active compensation profile</label><label>Notes<textarea name="notes" rows="3"></textarea></label><button class="button button-primary">Save compensation profile</button></form></section><section class="panel panel-wide"><h2>Current compensation profiles</h2><?php if(!$profiles){echo '<div class="empty">No compensation profiles yet. Add Nick and Adam at $18/hour if they were not matched automatically.</div>';}else{?><div class="table-wrap"><table><thead><tr><th>Glassblower</th><th>Hourly rate</th><th>Piecework eligible</th><th>Effective</th><th>Status</th></tr></thead><tbody><?php foreach($profiles as $r):$u=get_userdata((int)$r['user_id']);?><tr><td><strong><?php echo esc_html($u?$u->display_name:'Unknown user');?></strong></td><td>$<?php echo number_format_i18n((float)$r['hourly_rate'],2);?> / hour</td><td><?php echo $r['piecework_eligible']?'Yes':'No';?></td><td><?php echo esc_html($r['effective_date']?:'Unavailable');?></td><td><?php echo $r['active']?'Active':'Inactive';?></td></tr><?php endforeach;?></tbody></table></div><?php }?></section></div><?php
    }

    public static function save_product(): void { self::guard();check_admin_referer('elev8_save_production_product');$r=Elev8_OS_Production_Catalog_Service::save_product(wp_unslash($_POST));wp_safe_redirect(self::url(['view'=>is_wp_error($r)?'new-product':'edit-product','product_id'=>is_wp_error($r)?0:$r,'notice'=>is_wp_error($r)?$r->get_error_message():'Production product saved and versioned.']));exit; }
    public static function save_material(): void { self::guard();check_admin_referer('elev8_save_production_material');$r=Elev8_OS_Production_Catalog_Service::save_material(wp_unslash($_POST));wp_safe_redirect(self::url(['view'=>'materials','notice'=>is_wp_error($r)?$r->get_error_message():'Material saved.']));exit; }
    public static function save_profile(): void { self::guard();check_admin_referer('elev8_save_compensation_profile');$r=Elev8_OS_Production_Catalog_Service::save_compensation_profile(wp_unslash($_POST));wp_safe_redirect(self::url(['view'=>'compensation','notice'=>is_wp_error($r)?$r->get_error_message():'Compensation profile saved.']));exit; }
}
