<?php
if (!defined('ABSPATH')) { exit; }
final class Elev8_OS_Action_Center_Module {
    public static function init(): void {
        add_shortcode('elev8_action_center',[__CLASS__,'shortcode']);
        add_action('wp_enqueue_scripts',[__CLASS__,'assets']);
        add_action('admin_post_elev8_os_frontend_work_update',[__CLASS__,'update_work']);
        add_action('admin_post_elev8_os_frontend_work_create',[__CLASS__,'create_work']);
    }
    public static function url(array $args=[]): string {
        $base=class_exists('Elev8_OS_Portal_Page_Manager')?Elev8_OS_Portal_Page_Manager::get_url('actions'):home_url('/elev8-actions/');
        return $args?add_query_arg($args,$base):$base;
    }
    public static function assets(): void { if (class_exists('Elev8_OS_Portal_Page_Manager')&&Elev8_OS_Portal_Page_Manager::is_current_page('actions')) wp_enqueue_style('elev8-action-center',ELEV8_OS_URL.'assets/css/action-center.css',[],ELEV8_OS_VERSION); }
    public static function shortcode(): string {
        if (!is_user_logged_in()) return '<p>'.esc_html__('Please sign in to view your actions.','elev8-os').'</p>';
        $user=wp_get_current_user(); if(!Elev8_OS_Access_Service::user_can('view_work',$user)) return '<p>'.esc_html__('You do not have access to work actions.','elev8-os').'</p>';
        $team=Elev8_OS_Access_Service::user_can('manage_work',$user) && sanitize_key((string)($_GET['view']??''))==='team';
        $items=Elev8_OS_Action_Service::work_items($user,$team); $counts=Elev8_OS_Work_Service::counts($team?0:$user->ID);
        ob_start(); ?>
        <main class="elev8-action-center"><header><p class="eyebrow">ELEV8 OS ACTION ENGINE</p><h1><?php echo esc_html($team?__('Team Actions','elev8-os'):__('My Actions','elev8-os'));?></h1><p><?php esc_html_e('Information should lead directly to the next action. Review, update, assign, and complete work here without entering WordPress administration.','elev8-os');?></p></header>
        <nav class="action-tabs"><a class="<?php echo !$team?'is-active':'';?>" href="<?php echo esc_url(self::url());?>"><?php esc_html_e('My Actions','elev8-os');?></a><?php if(Elev8_OS_Access_Service::user_can('manage_work',$user)):?><a class="<?php echo $team?'is-active':'';?>" href="<?php echo esc_url(self::url(['view'=>'team']));?>"><?php esc_html_e('Team Actions','elev8-os');?></a><a href="<?php echo esc_url(admin_url('admin.php?page=elev8-daily-operations&view=brief'));?>"><?php esc_html_e('Manager Logs','elev8-os');?></a><?php endif;?></nav>
        <section class="action-metrics"><?php foreach(['overdue'=>'Overdue','due_today'=>'Due Today','active'=>'Active','waiting'=>'Waiting'] as $k=>$label):?><article><strong><?php echo (int)($counts[$k]??0);?></strong><span><?php echo esc_html($label);?></span></article><?php endforeach;?></section>
        <?php if($team):?><details class="action-create"><summary><?php esc_html_e('Create an action','elev8-os');?></summary><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><?php wp_nonce_field('elev8_frontend_work_create');?><input type="hidden" name="action" value="elev8_os_frontend_work_create"><label>Title<input name="title" required></label><label>Description<textarea name="description" rows="3"></textarea></label><label>Due date<input type="date" name="due_date"></label><label>Priority<select name="priority"><?php foreach(Elev8_OS_Work_Service::priorities() as $k=>$v):?><option value="<?php echo esc_attr($k);?>"><?php echo esc_html($v);?></option><?php endforeach;?></select></label><button>Create Action</button></form></details><?php endif;?>
        <section class="action-list"><?php if(!$items):?><div class="action-empty"><h2><?php esc_html_e('Nothing is waiting','elev8-os');?></h2><p><?php esc_html_e('There are no active work actions assigned here.','elev8-os');?></p></div><?php endif; foreach($items as $item): $status=(string)get_post_meta($item->ID,'_elev8_work_status',true)?:'new';$priority=(string)get_post_meta($item->ID,'_elev8_work_priority',true)?:'normal';$due=(string)get_post_meta($item->ID,'_elev8_work_due_date',true);?><article class="action-card"><header><div><span><?php echo esc_html(Elev8_OS_Work_Service::priorities()[$priority]??ucfirst($priority));?></span><h2><?php echo esc_html(get_the_title($item));?></h2></div><strong><?php echo esc_html(Elev8_OS_Work_Service::statuses()[$status]??ucfirst($status));?></strong></header><?php if($item->post_content):?><p><?php echo esc_html(wp_trim_words(wp_strip_all_tags($item->post_content),30));?></p><?php endif;?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><?php wp_nonce_field('elev8_frontend_work_update_'.$item->ID);?><input type="hidden" name="action" value="elev8_os_frontend_work_update"><input type="hidden" name="work_id" value="<?php echo (int)$item->ID;?>"><input type="hidden" name="team" value="<?php echo $team?'1':'0';?>"><label>Status<select name="status"><?php foreach(Elev8_OS_Work_Service::statuses() as $k=>$v):?><option value="<?php echo esc_attr($k);?>" <?php selected($status,$k);?>><?php echo esc_html($v);?></option><?php endforeach;?></select></label><label>Due<input type="date" name="due_date" value="<?php echo esc_attr($due);?>"></label><label>Notes<textarea name="notes" rows="2"></textarea></label><button><?php esc_html_e('Save Action','elev8-os');?></button></form></article><?php endforeach;?></section></main><?php return (string)ob_get_clean();
    }
    public static function update_work(): void { $id=absint($_POST['work_id']??0);check_admin_referer('elev8_frontend_work_update_'.$id);$owner=absint(get_post_meta($id,'_elev8_work_owner_user_id',true));$can=Elev8_OS_Access_Service::user_can('manage_work')||(Elev8_OS_Access_Service::user_can('view_work')&&$owner===get_current_user_id());if(!$can)wp_die('Permission denied.');Elev8_OS_Work_Service::update($id,['status'=>wp_unslash($_POST['status']??'new'),'due_date'=>wp_unslash($_POST['due_date']??''),'notes'=>wp_unslash($_POST['notes']??'')]);wp_safe_redirect(self::url(!empty($_POST['team'])?['view'=>'team']:[]));exit; }
    public static function create_work(): void { if(!Elev8_OS_Access_Service::user_can('manage_work'))wp_die('Permission denied.');check_admin_referer('elev8_frontend_work_create');Elev8_OS_Work_Service::create(['title'=>wp_unslash($_POST['title']??''),'description'=>wp_unslash($_POST['description']??''),'due_date'=>wp_unslash($_POST['due_date']??''),'priority'=>wp_unslash($_POST['priority']??'normal')]);wp_safe_redirect(self::url(['view'=>'team']));exit; }
}
