<?php
/**
 * Read-only access to release metadata generated by the Elev8 OS builder.
 *
 * The builder-owned release-manifest.json remains the single source of truth
 * for build metadata. This service never invents values when the manifest is
 * missing or malformed.
 *
 * @package Elev8OS
 */

if (!defined('ABSPATH')) {
    exit;
}

final class Elev8_OS_Release_Information_Service {

    /**
     * Return normalized release information for owner-facing interfaces.
     *
     * @return array<string,mixed>
     */
    public static function get_release_information(): array {
        $manifest = self::read_manifest();

        if ($manifest === null) {
            return [
                'available' => false,
                'diagnostic' => __('The release manifest is unavailable or could not be verified.', 'elev8-os'),
                'version' => defined('ELEV8_OS_VERSION') ? (string) ELEV8_OS_VERSION : '',
                'build' => '',
                'built_at_utc' => '',
                'branch' => '',
                'commit' => '',
                'working_tree_dirty' => null,
                'php_syntax' => '',
                'php_file_count' => null,
                'package' => '',
            ];
        }

        $git = isset($manifest['git']) && is_array($manifest['git']) ? $manifest['git'] : [];
        $validation = isset($manifest['validation']) && is_array($manifest['validation'])
            ? $manifest['validation']
            : [];

        return [
            'available' => true,
            'diagnostic' => __('Release metadata loaded from the packaged manifest.', 'elev8-os'),
            'version' => self::string_value($manifest, 'version'),
            'build' => self::string_value($manifest, 'build'),
            'built_at_utc' => self::string_value($manifest, 'builtAtUtc'),
            'branch' => self::string_value($git, 'branch'),
            'commit' => self::string_value($git, 'commit'),
            'working_tree_dirty' => array_key_exists('workingTreeDirty', $git)
                ? (bool) $git['workingTreeDirty']
                : null,
            'php_syntax' => self::string_value($validation, 'phpSyntax'),
            'php_file_count' => isset($validation['phpFileCount']) && is_numeric($validation['phpFileCount'])
                ? (int) $validation['phpFileCount']
                : null,
            'package' => self::string_value($manifest, 'package'),
        ];
    }

    /**
     * @return array<string,mixed>|null
     */
    private static function read_manifest(): ?array {
        $path = trailingslashit(ELEV8_OS_DIR) . 'release-manifest.json';

        if (!is_readable($path)) {
            return null;
        }

        $contents = file_get_contents($path);
        if (!is_string($contents) || trim($contents) === '') {
            return null;
        }

        $manifest = json_decode($contents, true);
        if (!is_array($manifest) || json_last_error() !== JSON_ERROR_NONE) {
            return null;
        }

        return $manifest;
    }

    /**
     * @param array<string,mixed> $source
     */
    private static function string_value(array $source, string $key): string {
        return isset($source[$key]) && is_scalar($source[$key])
            ? trim((string) $source[$key])
            : '';
    }
}
