<?php
/** Artist invitations and responses for Elev8 OS opportunities. */
if (!defined('ABSPATH')) { exit; }
final class Elev8_OS_Opportunity_Participation_Service {
    private const DB_VERSION='1.0.0'; private const DB_OPTION='elev8_os_opportunity_participation_db_version';
    private static function table(): string { global $wpdb; return $wpdb->prefix.'elev8_opportunity_invitations'; }
    public static function maybe_upgrade(): void { if (get_option(self::DB_OPTION)!==self::DB_VERSION) { self::create_table(); update_option(self::DB_OPTION,self::DB_VERSION,false); } }
    public static function activate(): void { self::create_table(); update_option(self::DB_OPTION,self::DB_VERSION,false); }
    private static function create_table(): void { global $wpdb; require_once ABSPATH.'wp-admin/includes/upgrade.php'; $t=self::table(); $c=$wpdb->get_charset_collate(); dbDelta("CREATE TABLE {$t} (
      id bigint(20) unsigned NOT NULL AUTO_INCREMENT, opportunity_id bigint(20) unsigned NOT NULL, user_id bigint(20) unsigned NOT NULL, artist_id bigint(20) unsigned NOT NULL DEFAULT 0,
      status varchar(30) NOT NULL DEFAULT 'pending', invited_at datetime NOT NULL, responded_at datetime DEFAULT NULL, reminder_sent_at datetime DEFAULT NULL, notes text NULL,
      PRIMARY KEY (id), UNIQUE KEY opportunity_user (opportunity_id,user_id), KEY opportunity_status (opportunity_id,status), KEY artist_id (artist_id)
    ) {$c};"); }
    public static function invite_user(int $opportunity_id,int $user_id,int $artist_id=0): int { global $wpdb; if($opportunity_id<=0||$user_id<=0)return 0; $wpdb->query($wpdb->prepare("INSERT INTO ".self::table()." (opportunity_id,user_id,artist_id,status,invited_at) VALUES (%d,%d,%d,'pending',%s) ON DUPLICATE KEY UPDATE artist_id=VALUES(artist_id)",$opportunity_id,$user_id,$artist_id,current_time('mysql'))); return (int)$wpdb->get_var($wpdb->prepare('SELECT id FROM '.self::table().' WHERE opportunity_id=%d AND user_id=%d',$opportunity_id,$user_id)); }
    public static function respond(int $opportunity_id,int $user_id,string $status): bool { global $wpdb; $allowed=['interested','confirmed','declined','remind_later']; if(!in_array($status,$allowed,true))return false; return false!==$wpdb->update(self::table(),['status'=>$status,'responded_at'=>current_time('mysql')],['opportunity_id'=>$opportunity_id,'user_id'=>$user_id],['%s','%s'],['%d','%d']); }
    public static function for_user(int $user_id,bool $upcoming_only=true): array { global $wpdb; if($user_id<=0)return []; $where=$upcoming_only?" AND (o.preferred_day='' OR o.preferred_day>=CURDATE()) AND o.status NOT IN ('completed','archived','cancelled')":''; $rows=$wpdb->get_results($wpdb->prepare('SELECT i.*,o.title,o.description,o.category,o.status opportunity_status,o.preferred_day event_date,o.preferred_time event_time,o.internal_notes,o.type FROM '.self::table().' i INNER JOIN '.$wpdb->prefix.'elev8_opportunities o ON o.id=i.opportunity_id WHERE i.user_id=%d'.$where.' ORDER BY CASE WHEN o.preferred_day="" THEN 1 ELSE 0 END,o.preferred_day ASC,o.id DESC',$user_id),ARRAY_A); return is_array($rows)?$rows:[]; }
    public static function for_opportunity(int $opportunity_id): array { global $wpdb; $rows=$wpdb->get_results($wpdb->prepare('SELECT i.*,u.display_name,u.user_email FROM '.self::table().' i LEFT JOIN '.$wpdb->users.' u ON u.ID=i.user_id WHERE i.opportunity_id=%d ORDER BY i.status,u.display_name',$opportunity_id),ARRAY_A); return is_array($rows)?$rows:[]; }
    public static function counts(int $opportunity_id): array { $out=['pending'=>0,'interested'=>0,'confirmed'=>0,'declined'=>0,'remind_later'=>0]; foreach(self::for_opportunity($opportunity_id) as $r){$k=(string)$r['status']; if(isset($out[$k]))$out[$k]++;} return $out; }
    public static function artist_users(): array { global $wpdb; $rows=$wpdb->get_results($wpdb->prepare("SELECT DISTINCT u.ID,u.display_name,u.user_email,CAST(um.meta_value AS UNSIGNED) artist_id FROM {$wpdb->users} u INNER JOIN {$wpdb->usermeta} um ON um.user_id=u.ID AND um.meta_key=%s WHERE CAST(um.meta_value AS UNSIGNED)>0 ORDER BY u.display_name",'elev8_os_amelia_employee_id'),ARRAY_A); return is_array($rows)?$rows:[]; }
}
